export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-DardcorCode-Cache",
  cacheHit: "X-DardcorCode-Cache-Hit",
  compression: "X-DardcorCode-Compression",
  costSaved: "X-DardcorCode-Cost-Saved",
  decision: "X-DardcorCode-Decision",
  fallbackAttempts: "X-DardcorCode-Fallback-Attempts",
  latencyMs: "X-DardcorCode-Latency-Ms",
  model: "X-DardcorCode-Model",
  progress: "X-DardcorCode-Progress",
  provider: "X-DardcorCode-Provider",
  requestId: "X-DardcorCode-Request-Id",
  responseCost: "X-DardcorCode-Response-Cost",
  tokensIn: "X-DardcorCode-Tokens-In",
  tokensOut: "X-DardcorCode-Tokens-Out",
  version: "X-DardcorCode-Version",
} as const;
