export function hasToIgnoreCase() {}
export function originalFSPath() {}
export function joinPath() {}
export function extname() {}
export function basename() {}
export function dirname() {}
export function toLocalResource() {}
export function addTrailingPathSeparator() {}
export function removeTrailingPathSeparator() {}
export function isEqual() {}
export function isEqualOrParent() {}
export function isParent() {}
export function isEqualOrAncestor() {}
export function getComparisonKey() {}
export function distinctParents() {}
export function commonPrefixLength() {}
