export function consumeStream() {}
export function peekStream() {}
export function toStream() {}
export function isReadableStream() {}
export function listenStream() {}
export function writeToStream() {}
export function cancelStream() {}
export function join() {}
export function toArray() {}
