export function compare() {}
export function compareIgnoreCase() {}
export function compareSubstring() {}
export function lastIndex() {}
export function equalsIgnoreCase() {}
export function startsWith() {}
export function endsWith() {}
export function ltrim() {}
export function rtrim() {}
export function trim() {}
export function repeat() {}
export function padStart() {}
export function padEnd() {}
export function format() {}
export function contains() {}
export function isWhitespace() {}
export function isFalsyOrWhitespace() {}
export function convertSimple2RegExpPattern() {}
export function isDigit() {}
export function escapeRegExpCharacters() {}
export function randomString() {}
export function getRandomHexString() {}
export function truncate() {}
export function equals() {}
export function countLines() {}
export function capitalize() {}
export function matchesFuzzy() {}
export function commonPrefixLength() {}
export function commonSuffixLength() {}
export function nextLetter() {}
export function extName() {}
export function hash() {}
