export function isString() {}
export function isNumber() {}
export function isBoolean() {}
export function isFunction() {}
export function isObject() {}
export function isArray() {}
export function isUndefined() {}
export function isUndefinedOrNull() {}
export function isDefined() {}
export function isThenable() {}
export function isPromiseCancelable() {}
export function withNullAsUndefined() {}
export function withUndefinedAsNull() {}
export function getOrDefault() {}
export function isNonEmptyArray() {}
export function isNonEmptyString() {}
export function isUri() {}
