/**
 * Dardcor Code - Top Drop-Down Main Menu Bar
 */

import { Disposable } from '../../../core/lifecycle/disposable';
import { Emitter, Event } from '../../../core/events/emitter';
import { MenubarControl, IMenuEntry, IMenuItem, IMenuSelectionEvent } from '../titlebar/menubar-control';

export class MenubarPart extends Disposable {
	private readonly _control: MenubarControl;
	private readonly _onDidSelectMenu = this._register(new Emitter<IMenuSelectionEvent>());
	readonly onDidSelectMenu: Event<IMenuSelectionEvent> = this._onDidSelectMenu.event;

	constructor(parent: HTMLElement) {
		super();
		this._control = new MenubarControl(parent, MenubarPart.createDefaultMenus());
		this._register(this._control);
		this._control.onDidSelect(e => this._onDidSelectMenu.fire(e));
	}

	get control(): MenubarControl {
		return this._control;
	}

	setVisible(visible: boolean): void {
		this._control.setVisible(visible);
	}

	setMenus(entries: IMenuEntry[]): void {
		this._control.setEntries(entries);
	}

	static createDefaultMenus(): IMenuEntry[] {
		return [
			{
				id: 'file',
				title: 'File',
				children: [
					{ id: 'file.newTextFile', label: 'New Text File', keybinding: 'Ctrl+N' },
					{ id: 'file.newFile', label: 'New File...', keybinding: 'Ctrl+Alt+Win+N' },
					{ id: 'file.newWindow', label: 'New Window', keybinding: 'Ctrl+Shift+N' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'file.openFile', label: 'Open File...', keybinding: 'Ctrl+O' },
					{ id: 'file.openFolder', label: 'Open Folder...', keybinding: 'Ctrl+K Ctrl+O' },
					{ id: 'file.openWorkspace', label: 'Open Workspace from File...' },
					{ id: 'file.openRecent', label: 'Open Recent', children: [
						{ id: 'file.openRecent.file', label: 'Reopen Closed File' },
						{ id: 'file.openRecent.folder', label: 'Reopen Closed Folder' },
						{ id: 'file.openRecent.workspace', label: 'Reopen Closed Workspace' },
						{ id: 'sep1', label: '', separator: true },
						{ id: 'file.openRecent.clear', label: 'Clear Recently Opened' }
					] },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'file.addFolderToWorkspace', label: 'Add Folder to Workspace...' },
					{ id: 'file.saveWorkspaceAs', label: 'Save Workspace As...' },
					{ id: 'file.duplicateWorkspace', label: 'Duplicate Workspace' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'file.save', label: 'Save', keybinding: 'Ctrl+S' },
					{ id: 'file.saveAs', label: 'Save As...', keybinding: 'Ctrl+Shift+S' },
					{ id: 'file.saveAll', label: 'Save All', keybinding: 'Ctrl+K S' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'file.share', label: 'Share', children: [] },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'file.autoSave', label: 'Auto Save', children: [
						{ id: 'file.autoSave.off', label: 'Off' },
						{ id: 'file.autoSave.afterDelay', label: 'After Delay' },
						{ id: 'file.autoSave.onFocusChange', label: 'On Focus Change' },
						{ id: 'file.autoSave.onWindowChange', label: 'On Window Change' }
					] },
					{ id: 'file.preferences', label: 'Preferences', children: [
						{ id: 'file.preferences.settings', label: 'Settings', keybinding: 'Ctrl+,' },
						{ id: 'file.preferences.settingsSync', label: 'Settings Sync' },
						{ id: 'file.preferences.onlineServices', label: 'Online Services Settings' },
						{ id: 'sep1', label: '', separator: true },
						{ id: 'file.preferences.keyboardShortcuts', label: 'Keyboard Shortcuts', keybinding: 'Ctrl+K Ctrl+S' },
						{ id: 'sep2', label: '', separator: true },
						{ id: 'file.preferences.colorTheme', label: 'Color Theme', keybinding: 'Ctrl+K Ctrl+T' },
						{ id: 'file.preferences.fileIconTheme', label: 'File Icon Theme' },
						{ id: 'file.preferences.productIconTheme', label: 'Product Icon Theme' },
						{ id: 'sep3', label: '', separator: true },
						{ id: 'file.preferences.profile', label: 'Profile (Default)' }
					] },
					{ id: 'sep6', label: '', separator: true },
					{ id: 'file.revertFile', label: 'Revert File' },
					{ id: 'file.closeEditor', label: 'Close Editor', keybinding: 'Ctrl+F4' },
					{ id: 'file.closeFolder', label: 'Close Folder', keybinding: 'Ctrl+K F' },
					{ id: 'file.closeWindow', label: 'Close Window', keybinding: 'Alt+F4' },
					{ id: 'sep7', label: '', separator: true },
					{ id: 'file.exit', label: 'Exit' },
				],
			},
			{
				id: 'edit',
				title: 'Edit',
				children: [
					{ id: 'edit.undo', label: 'Undo', keybinding: 'Ctrl+Z' },
					{ id: 'edit.redo', label: 'Redo', keybinding: 'Ctrl+Y' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'edit.cut', label: 'Cut', keybinding: 'Ctrl+X' },
					{ id: 'edit.copy', label: 'Copy', keybinding: 'Ctrl+C' },
					{ id: 'edit.paste', label: 'Paste', keybinding: 'Ctrl+V' },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'edit.find', label: 'Find', keybinding: 'Ctrl+F' },
					{ id: 'edit.replace', label: 'Replace', keybinding: 'Ctrl+H' },
					{ id: 'edit.findInFiles', label: 'Find in Files', keybinding: 'Ctrl+Shift+F' },
					{ id: 'edit.replaceInFiles', label: 'Replace in Files', keybinding: 'Ctrl+Shift+H' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'edit.findNext', label: 'Find Next', keybinding: 'F3' },
					{ id: 'edit.findPrevious', label: 'Find Previous', keybinding: 'Shift+F3' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'edit.selectAll', label: 'Select All', keybinding: 'Ctrl+A' },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'edit.toggleLineComment', label: 'Toggle Line Comment', keybinding: 'Ctrl+/' },
					{ id: 'edit.toggleBlockComment', label: 'Toggle Block Comment', keybinding: 'Shift+Alt+A' },
					{ id: 'sep6', label: '', separator: true },
					{ id: 'edit.emmetExpandAbbreviation', label: 'Emmet: Expand Abbreviation', keybinding: 'Tab' },
					{ id: 'edit.emmetWrapWithAbbreviation', label: 'Emmet: Wrap with Abbreviation' },
					{ id: 'edit.emmetBalanceOutward', label: 'Emmet: Balance (Outward)' },
					{ id: 'edit.emmetBalanceInward', label: 'Emmet: Balance (Inward)' },
					{ id: 'edit.emmetUpdateImageSize', label: 'Emmet: Update Image Size' },
					{ id: 'edit.emmetGoToMatchingPair', label: 'Emmet: Go to Matching Pair' },
					{ id: 'edit.emmetSelectNextItem', label: 'Emmet: Select Next Item' },
					{ id: 'edit.emmetSelectPreviousItem', label: 'Emmet: Select Previous Item' },
					{ id: 'edit.emmetRemoveTag', label: 'Emmet: Remove Tag' },
					{ id: 'edit.emmetSplitJoinTag', label: 'Emmet: Split/Join Tag' },
					{ id: 'edit.emmetTrimTag', label: 'Emmet: Trim Tag' },
					{ id: 'edit.emmetReflectCSSValue', label: 'Emmet: Reflect CSS Value' },
					{ id: 'edit.emmetPreviewHTML', label: 'Emmet: Preview HTML' },
					{ id: 'edit.emmetUpdateTag', label: 'Emmet: Update Tag' },
					{ id: 'edit.emmetExpandAbbreviationSnippet', label: 'Emmet: Expand Abbreviation (Snippet)' },
					{ id: 'sep7', label: '', separator: true },
					{ id: 'edit.advanced', label: 'Advanced', children: [
						{ id: 'edit.advanced.changeLanguageMode', label: 'Change Language Mode' },
						{ id: 'edit.advanced.changeEncoding', label: 'Change Encoding' },
						{ id: 'edit.advanced.convertFileEncoding', label: 'Convert File Encoding' },
						{ id: 'edit.advanced.reopenWithEncoding', label: 'Reopen with Encoding' },
						{ id: 'edit.advanced.saveWithEncoding', label: 'Save with Encoding' },
						{ id: 'sep1', label: '', separator: true },
						{ id: 'edit.advanced.goToSymbol', label: 'Go to Symbol' },
						{ id: 'edit.advanced.goToDefinition', label: 'Go to Definition' },
						{ id: 'edit.advanced.goToTypeDefinition', label: 'Go to Type Definition' },
						{ id: 'edit.advanced.goToImplementation', label: 'Go to Implementation' },
						{ id: 'edit.advanced.goToReferences', label: 'Go to References' },
						{ id: 'edit.advanced.findAllReferences', label: 'Find All References' },
						{ id: 'sep2', label: '', separator: true },
						{ id: 'edit.advanced.changeAllOccurrences', label: 'Change All Occurrences' },
						{ id: 'edit.advanced.renameSymbol', label: 'Rename Symbol' },
						{ id: 'sep3', label: '', separator: true },
						{ id: 'edit.advanced.organizeImports', label: 'Organize Imports' },
						{ id: 'edit.advanced.formatDocument', label: 'Format Document' },
						{ id: 'edit.advanced.formatSelection', label: 'Format Selection' },
						{ id: 'edit.advanced.trimTrailingWhitespace', label: 'Trim Trailing Whitespace' },
						{ id: 'sep4', label: '', separator: true },
						{ id: 'edit.advanced.convertIndentationToSpaces', label: 'Convert Indentation to Spaces' },
						{ id: 'edit.advanced.convertIndentationToTabs', label: 'Convert Indentation to Tabs' },
						{ id: 'sep5', label: '', separator: true },
						{ id: 'edit.advanced.invisibleCharacters', label: 'Invisible Characters' },
						{ id: 'edit.advanced.renderWhitespace', label: 'Render Whitespace' },
						{ id: 'sep6', label: '', separator: true },
						{ id: 'edit.advanced.wordWrap', label: 'Word Wrap' },
						{ id: 'edit.advanced.toggleWordWrap', label: 'Toggle Word Wrap' }
					] }
				],
			},
			{
				id: 'view',
				title: 'View',
				children: [
					{ id: 'view.commandPalette', label: 'Command Palette...', keybinding: 'Ctrl+Shift+P' },
					{ id: 'view.openView', label: 'Open View...' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'view.appearance', label: 'Appearance', children: [
						{ id: 'view.appearance.fullScreen', label: 'Full Screen' },
						{ id: 'view.appearance.zoomIn', label: 'Zoom In' },
						{ id: 'view.appearance.zoomOut', label: 'Zoom Out' },
						{ id: 'view.appearance.resetZoom', label: 'Reset Zoom' },
						{ id: 'sep1', label: '', separator: true },
						{ id: 'view.appearance.centeredLayout', label: 'Centered Layout' },
						{ id: 'view.appearance.zenMode', label: 'Zen Mode' },
						{ id: 'view.appearance.closeZenMode', label: 'Close Zen Mode' },
						{ id: 'sep2', label: '', separator: true },
						{ id: 'view.appearance.menuBar', label: 'Menu Bar' },
						{ id: 'view.appearance.activityBar', label: 'Activity Bar' },
						{ id: 'view.appearance.statusBar', label: 'Status Bar' },
						{ id: 'view.appearance.panel', label: 'Panel' },
						{ id: 'view.appearance.sideBar', label: 'Side Bar' },
						{ id: 'view.appearance.primarySideBar', label: 'Primary Side Bar' },
						{ id: 'view.appearance.secondarySideBar', label: 'Secondary Side Bar' },
						{ id: 'sep3', label: '', separator: true },
						{ id: 'view.appearance.editorLayout', label: 'Editor Layout' },
						{ id: 'view.appearance.toggleStatusBar', label: 'Toggle Status Bar' },
						{ id: 'view.appearance.toggleActivityBar', label: 'Toggle Activity Bar' },
						{ id: 'view.appearance.togglePanel', label: 'Toggle Panel' },
						{ id: 'view.appearance.toggleSideBar', label: 'Toggle Side Bar' }
					] },
					{ id: 'view.editorLayout', label: 'Editor Layout', children: [
						{ id: 'view.editorLayout.single', label: 'Single' },
						{ id: 'view.editorLayout.splitEditorRight', label: 'Split Editor Right' },
						{ id: 'view.editorLayout.splitEditorDown', label: 'Split Editor Down' },
						{ id: 'view.editorLayout.twoColumns', label: 'Two Columns' },
						{ id: 'view.editorLayout.threeColumns', label: 'Three Columns' },
						{ id: 'view.editorLayout.twoRows', label: 'Two Rows' },
						{ id: 'view.editorLayout.threeRows', label: 'Three Rows' },
						{ id: 'view.editorLayout.twoRowsRight', label: 'Two Rows Right' },
						{ id: 'view.editorLayout.twoColumnsBottom', label: 'Two Columns Bottom' },
						{ id: 'view.editorLayout.fourGrid', label: 'Four Grid' },
						{ id: 'view.editorLayout.grid', label: 'Grid' },
						{ id: 'sep1', label: '', separator: true },
						{ id: 'view.editorLayout.flipLayout', label: 'Flip Layout' },
						{ id: 'sep2', label: '', separator: true },
						{ id: 'view.editorLayout.groupMax', label: 'Group Max' },
						{ id: 'view.editorLayout.groupMin', label: 'Group Min' },
						{ id: 'sep3', label: '', separator: true },
						{ id: 'view.editorLayout.resetEditorLayout', label: 'Reset Editor Layout' }
					] },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'view.explorer', label: 'Explorer', keybinding: 'Ctrl+Shift+E' },
					{ id: 'view.search', label: 'Search', keybinding: 'Ctrl+Shift+F' },
					{ id: 'view.sourceControl', label: 'Source Control', keybinding: 'Ctrl+Shift+G' },
					{ id: 'view.run', label: 'Run', keybinding: 'Ctrl+Shift+D' },
					{ id: 'view.extensions', label: 'Extensions', keybinding: 'Ctrl+Shift+X' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'view.output', label: 'Output', keybinding: 'Ctrl+Shift+U' },
					{ id: 'view.debugConsole', label: 'Debug Console', keybinding: 'Ctrl+Shift+Y' },
					{ id: 'view.problems', label: 'Problems', keybinding: 'Ctrl+Shift+M' },
					{ id: 'view.terminal', label: 'Terminal', keybinding: 'Ctrl+`' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'view.timeline', label: 'Timeline' },
					{ id: 'view.outline', label: 'Outline' },
					{ id: 'view.scm', label: 'SCM' },
					{ id: 'view.testing', label: 'Testing' },
					{ id: 'view.remote', label: 'Remote' },
					{ id: 'view.chat', label: 'Chat' },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'view.maximizeEditorGroup', label: 'Maximize Editor Group' },
					{ id: 'view.minimizeEditorGroup', label: 'Minimize Editor Group' },
					{ id: 'sep6', label: '', separator: true },
					{ id: 'view.nextEditor', label: 'Next Editor', keybinding: 'Ctrl+PageDown' },
					{ id: 'view.previousEditor', label: 'Previous Editor', keybinding: 'Ctrl+PageUp' },
					{ id: 'view.openNextEditor', label: 'Open Next Editor', keybinding: 'Ctrl+Alt+PageDown' },
					{ id: 'view.openPreviousEditor', label: 'Open Previous Editor', keybinding: 'Ctrl+Alt+PageUp' },
					{ id: 'view.showOpenedEditors', label: 'Show Opened Editors' },
					{ id: 'sep7', label: '', separator: true },
					{ id: 'view.moveEditorIntoNextGroup', label: 'Move Editor into Next Group' },
					{ id: 'view.moveEditorIntoPreviousGroup', label: 'Move Editor into Previous Group' },
					{ id: 'view.moveEditorRight', label: 'Move Editor Right' },
					{ id: 'view.moveEditorLeft', label: 'Move Editor Left' },
					{ id: 'sep8', label: '', separator: true },
					{ id: 'view.panel', label: 'Panel', children: [
						{ id: 'view.panel.output', label: 'Output' },
						{ id: 'view.panel.problems', label: 'Problems' },
						{ id: 'view.panel.terminal', label: 'Terminal' },
						{ id: 'view.panel.debugConsole', label: 'Debug Console' },
						{ id: 'sep1', label: '', separator: true },
						{ id: 'view.panel.alignPanel', label: 'Align Panel' }
					] },
					{ id: 'view.togglePrimarySideBar', label: 'Toggle Primary Side Bar', keybinding: 'Ctrl+B' },
					{ id: 'view.toggleSecondarySideBar', label: 'Toggle Secondary Side Bar' },
					{ id: 'view.toggleZenMode', label: 'Toggle Zen Mode', keybinding: 'Ctrl+K Z' },
					{ id: 'sep9', label: '', separator: true },
					{ id: 'view.zoomOutAction', label: 'Zoom Out', keybinding: 'Ctrl+-' },
					{ id: 'view.zoomInAction', label: 'Zoom In', keybinding: 'Ctrl+=' },
					{ id: 'view.resetZoom', label: 'Reset Zoom', keybinding: 'Ctrl+0' },
					{ id: 'sep10', label: '', separator: true },
					{ id: 'view.switchToOtherView', label: 'Switch to Other View' },
					{ id: 'view.showPanel', label: 'Show Panel' },
					{ id: 'view.togglePanelAction', label: 'Toggle Panel' },
					{ id: 'view.toggleStatusBar', label: 'Toggle Status Bar' },
					{ id: 'view.toggleActivityBar', label: 'Toggle Activity Bar' },
					{ id: 'view.toggleMenuBar', label: 'Toggle Menu Bar' },
					{ id: 'view.toggleBreadcrumbs', label: 'Toggle Breadcrumbs' },
					{ id: 'view.toggleStickyScroll', label: 'Toggle Sticky Scroll' },
					{ id: 'view.toggleWordWrap', label: 'Toggle Word Wrap' },
					{ id: 'view.toggleMinimap', label: 'Toggle Minimap' },
					{ id: 'view.toggleRenderWhitespace', label: 'Toggle Render Whitespace' },
					{ id: 'view.toggleRenderControlCharacters', label: 'Toggle Render Control Characters' },
					{ id: 'view.toggleSmoothScrolling', label: 'Toggle Smooth Scrolling' },
					{ id: 'view.toggleScrollBeyondLastLine', label: 'Toggle Scroll Beyond Last Line' },
					{ id: 'view.toggleLargeFileOptimizations', label: 'Toggle Large File Optimizations' }
				],
			},
			{
				id: 'selection',
				title: 'Selection',
				children: [
					{ id: 'selection.selectAll', label: 'Select All', keybinding: 'Ctrl+A' },
					{ id: 'selection.expandSelection', label: 'Expand Selection', keybinding: 'Shift+Alt+Right' },
					{ id: 'selection.shrinkSelection', label: 'Shrink Selection', keybinding: 'Shift+Alt+Left' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'selection.copyLineUp', label: 'Copy Line Up', keybinding: 'Shift+Alt+Up' },
					{ id: 'selection.copyLineDown', label: 'Copy Line Down', keybinding: 'Shift+Alt+Down' },
					{ id: 'selection.moveLineUp', label: 'Move Line Up', keybinding: 'Alt+Up' },
					{ id: 'selection.moveLineDown', label: 'Move Line Down', keybinding: 'Alt+Down' },
					{ id: 'selection.duplicateSelection', label: 'Duplicate Selection' },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'selection.addCursorAbove', label: 'Add Cursor Above', keybinding: 'Ctrl+Alt+Up' },
					{ id: 'selection.addCursorBelow', label: 'Add Cursor Below', keybinding: 'Ctrl+Alt+Down' },
					{ id: 'selection.addCursorToLineEnds', label: 'Add Cursor to Line Ends', keybinding: 'Shift+Alt+I' },
					{ id: 'selection.addNextOccurrence', label: 'Add Next Occurrence', keybinding: 'Ctrl+D' },
					{ id: 'selection.addPreviousOccurrence', label: 'Add Previous Occurrence', keybinding: 'Ctrl+Shift+D' },
					{ id: 'selection.selectAllOccurrences', label: 'Select All Occurrences', keybinding: 'Ctrl+Shift+L' },
					{ id: 'selection.addCursorAtBottom', label: 'Add Cursor at Bottom', keybinding: 'Ctrl+Shift+End' },
					{ id: 'selection.addCursorAtTop', label: 'Add Cursor at Top', keybinding: 'Ctrl+Shift+Home' },
					{ id: 'selection.columnSelectionMode', label: 'Column Selection Mode', keybinding: 'Shift+Alt' },
					{ id: 'selection.switchCmdClick', label: 'Switch to Cmd+Click' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'selection.convertCase', label: 'Convert Case', children: [
						{ id: 'selection.convertCase.upper', label: 'Upper Case' },
						{ id: 'selection.convertCase.lower', label: 'Lower Case' },
						{ id: 'selection.convertCase.title', label: 'Title Case' }
					] },
					{ id: 'selection.splitSelectionIntoLines', label: 'Split Selection into Lines' },
					{ id: 'selection.expandToLine', label: 'Expand to Line' },
					{ id: 'selection.shrinkToLine', label: 'Shrink to Line' },
					{ id: 'selection.selectToBracket', label: 'Select to Bracket' },
					{ id: 'selection.selectToMatchingBracket', label: 'Select to Matching Bracket' }
				],
			},
			{
				id: 'go',
				title: 'Go',
				children: [
					{ id: 'go.back', label: 'Back', keybinding: 'Alt+\u2190' },
					{ id: 'go.forward', label: 'Forward', keybinding: 'Alt+\u2192' },
					{ id: 'go.lastEditLocation', label: 'Last Edit Location', keybinding: 'Ctrl+K Ctrl+Q' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'go.switchEditor', label: 'Switch Editor', keybinding: 'Ctrl+Tab' },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'go.goToFile', label: 'Go to File...', keybinding: 'Ctrl+P' },
					{ id: 'go.goToSymbolInFile', label: 'Go to Symbol in File...', keybinding: 'Ctrl+Shift+O' },
					{ id: 'go.goToSymbolInWorkspace', label: 'Go to Symbol in Workspace...', keybinding: 'Ctrl+T' },
					{ id: 'go.goToLineColumn', label: 'Go to Line/Column...', keybinding: 'Ctrl+G' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'go.goToDefinition', label: 'Go to Definition', keybinding: 'F12' },
					{ id: 'go.goToDefinitionInSidePeek', label: 'Go to Definition in Side Peek', keybinding: 'Alt+F12' },
					{ id: 'go.peekDefinition', label: 'Peek Definition', keybinding: 'Alt+F12' },
					{ id: 'go.goToImplementation', label: 'Go to Implementation', keybinding: 'Ctrl+F12' },
					{ id: 'go.goToTypeDefinition', label: 'Go to Type Definition', keybinding: 'Ctrl+Shift+F12' },
					{ id: 'go.goToReferences', label: 'Go to References', keybinding: 'Shift+F12' },
					{ id: 'go.findAllReferences', label: 'Find All References', keybinding: 'Shift+Alt+F12' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'go.goToBracket', label: 'Go to Bracket', keybinding: 'Ctrl+Shift+\\' },
					{ id: 'go.goToMatchingBracket', label: 'Go to Matching Bracket' },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'go.goToNextProblem', label: 'Go to Next Problem', keybinding: 'F8' },
					{ id: 'go.goToPreviousProblem', label: 'Go to Previous Problem', keybinding: 'Shift+F8' },
					{ id: 'sep6', label: '', separator: true },
					{ id: 'go.nextDifference', label: 'Next Difference', keybinding: 'F7' },
					{ id: 'go.previousDifference', label: 'Previous Difference', keybinding: 'Shift+F7' },
					{ id: 'sep7', label: '', separator: true },
					{ id: 'go.nextEditorGroup', label: 'Next Editor Group' },
					{ id: 'go.previousEditorGroup', label: 'Previous Editor Group' },
					{ id: 'sep8', label: '', separator: true },
					{ id: 'go.nextSymbolHighlight', label: 'Next Symbol Highlight' },
					{ id: 'go.previousSymbolHighlight', label: 'Previous Symbol Highlight' },
					{ id: 'sep9', label: '', separator: true },
					{ id: 'go.nextFoldingRange', label: 'Next Folding Range', keybinding: 'Ctrl+Alt+[' },
					{ id: 'go.previousFoldingRange', label: 'Previous Folding Range', keybinding: 'Ctrl+Alt+]' },
					{ id: 'sep10', label: '', separator: true },
					{ id: 'go.nextSearchResult', label: 'Next Search Result' },
					{ id: 'go.previousSearchResult', label: 'Previous Search Result' },
					{ id: 'sep11', label: '', separator: true },
					{ id: 'go.nextChange', label: 'Next Change' },
					{ id: 'go.previousChange', label: 'Previous Change' }
				]
			},
			{
				id: 'run',
				title: 'Run',
				children: [
					{ id: 'run.startDebugging', label: 'Start Debugging', keybinding: 'F5' },
					{ id: 'run.runWithoutDebugging', label: 'Run Without Debugging', keybinding: 'Ctrl+F5' },
					{ id: 'run.stopDebugging', label: 'Stop Debugging', keybinding: 'Shift+F5' },
					{ id: 'run.restartDebugging', label: 'Restart Debugging', keybinding: 'Ctrl+Shift+F5' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'run.openConfigurations', label: 'Open Configurations' },
					{ id: 'run.addConfiguration', label: 'Add Configuration' },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'run.stepOver', label: 'Step Over', keybinding: 'F10' },
					{ id: 'run.stepInto', label: 'Step Into', keybinding: 'F11' },
					{ id: 'run.stepOut', label: 'Step Out', keybinding: 'Shift+F11' },
					{ id: 'run.continue', label: 'Continue', keybinding: 'F5' },
					{ id: 'run.pause', label: 'Pause' },
					{ id: 'run.restartFrame', label: 'Restart Frame' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'run.runTask', label: 'Run Task...' },
					{ id: 'run.toggleAutoAttach', label: 'Toggle Auto Attach' },
					{ id: 'run.attachToNodeJsProcess', label: 'Attach to Node.js Process' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'run.toggleBreakpoint', label: 'Toggle Breakpoint', keybinding: 'F9' },
					{ id: 'run.enableDisableBreakpoint', label: 'Enable/Disable Breakpoint' },
					{ id: 'run.addFunctionBreakpoint', label: 'Add Function Breakpoint' },
					{ id: 'run.addConditionalBreakpoint', label: 'Add Conditional Breakpoint' },
					{ id: 'run.addLogpoint', label: 'Add Logpoint' },
					{ id: 'run.editBreakpoint', label: 'Edit Breakpoint' },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'run.runAndDebug', label: 'Run and Debug' }
				]
			},
			{
				id: 'terminal',
				title: 'Terminal',
				children: [
					{ id: 'terminal.newTerminal', label: 'New Terminal', keybinding: 'Ctrl+Shift+`' },
					{ id: 'terminal.newTerminalInActiveWorkspace', label: 'New Terminal (In Active Workspace)' },
					{ id: 'terminal.splitTerminal', label: 'Split Terminal', keybinding: 'Ctrl+Shift+5' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'terminal.selectDefaultProfile', label: 'Select Default Profile' },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'terminal.runTask', label: 'Run Task' },
					{ id: 'terminal.runBuildTask', label: 'Run Build Task', keybinding: 'Ctrl+Shift+B' },
					{ id: 'terminal.runTestTask', label: 'Run Test Task' },
					{ id: 'terminal.showRunningTasks', label: 'Show Running Tasks' },
					{ id: 'terminal.restartRunningTask', label: 'Restart Running Task' },
					{ id: 'terminal.terminateTask', label: 'Terminate Task' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'terminal.killTerminal', label: 'Kill Terminal' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'terminal.copySelection', label: 'Copy Selection', keybinding: 'Ctrl+Shift+C' },
					{ id: 'terminal.paste', label: 'Paste', keybinding: 'Ctrl+Shift+V' },
					{ id: 'terminal.selectAll', label: 'Select All' },
					{ id: 'terminal.clear', label: 'Clear' },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'terminal.scrollUp', label: 'Scroll Up', keybinding: 'Ctrl+Shift+PageUp' },
					{ id: 'terminal.scrollDown', label: 'Scroll Down', keybinding: 'Ctrl+Shift+PageDown' },
					{ id: 'terminal.scrollToTop', label: 'Scroll to Top' },
					{ id: 'terminal.scrollToBottom', label: 'Scroll to Bottom' },
					{ id: 'sep6', label: '', separator: true },
					{ id: 'terminal.find', label: 'Find', keybinding: 'Ctrl+Shift+F' },
					{ id: 'terminal.toggleSizeToContentWidth', label: 'Toggle Size to Content Width' },
					{ id: 'sep7', label: '', separator: true },
					{ id: 'terminal.switchToSession', label: 'Switch to Session' },
					{ id: 'terminal.moveTerminalEditor', label: 'Move Terminal Editor' },
					{ id: 'terminal.changeIcon', label: 'Change Icon' },
					{ id: 'terminal.changeColor', label: 'Change Color' },
					{ id: 'terminal.rename', label: 'Rename' },
					{ id: 'terminal.showLogs', label: 'Show Logs' }
				]
			},
			{
				id: 'help',
				title: 'Help',
				children: [
					{ id: 'help.welcome', label: 'Welcome' },
					{ id: 'help.showAllCommands', label: 'Show All Commands' },
					{ id: 'help.documentation', label: 'Documentation' },
					{ id: 'help.releaseNotes', label: 'Release Notes' },
					{ id: 'sep1', label: '', separator: true },
					{ id: 'help.keyboardShortcutsReference', label: 'Keyboard Shortcuts Reference', keybinding: 'Ctrl+K Ctrl+R' },
					{ id: 'sep2', label: '', separator: true },
					{ id: 'help.introductoryVideos', label: 'Introductory Videos' },
					{ id: 'help.tipsAndTricks', label: 'Tips and Tricks' },
					{ id: 'help.joinUsOnYoutube', label: 'Join Us on YouTube' },
					{ id: 'sep3', label: '', separator: true },
					{ id: 'help.reportIssue', label: 'Report Issue' },
					{ id: 'help.viewLicense', label: 'View License' },
					{ id: 'help.privacyStatement', label: 'Privacy Statement' },
					{ id: 'sep4', label: '', separator: true },
					{ id: 'help.twitter', label: 'Twitter' },
					{ id: 'help.explore', label: 'Explore' },
					{ id: 'help.about', label: 'About Dardcor Code' },
					{ id: 'sep5', label: '', separator: true },
					{ id: 'help.openProcessExplorer', label: 'Open Process Explorer' },
					{ id: 'help.checkForUpdates', label: 'Check for Updates' },
					{ id: 'help.switchToInsidersChannel', label: 'Switch to Insiders Channel' },
					{ id: 'sep6', label: '', separator: true },
					{ id: 'help.resetLayout', label: 'Reset Layout' },
					{ id: 'help.usingDardcorCode', label: 'Using Dardcor Code' },
					{ id: 'sep7', label: '', separator: true },
					{ id: 'help.developerTools', label: 'Developer Tools' },
					{ id: 'help.toggleDeveloperTools', label: 'Toggle Developer Tools' }
				],
			},
		];
	}
}

export type { IMenuEntry, IMenuItem } from '../titlebar/menubar-control';
