"""Central provider registry for Dardcor Code.

Each entry defines display metadata, base_url, and a curated model list.
All non-Antigravity providers use StandardOpenAIProvider (OpenAI-compatible API).
Models marked with (Free) work without payment on the provider's free tier.
"""

PROVIDER_REGISTRY = {
    # ─── Special / OAuth-gated ─────────────────────────────────────────────────
    "Antigravity": {
        "name": "Antigravity",
        "icon": "✦",
        "color": "#8b5cf6",
        "base_url": "",
        "api_key_env": "",
        "is_special": True,
        "models": [
            # Gemini 3.5 Flash family
            {"id": "Gemini 3.5 Flash (High)",    "name": "Gemini 3.5 Flash (High)"},
            {"id": "Gemini 3.5 Flash (Medium)",  "name": "Gemini 3.5 Flash (Medium)"},
            {"id": "Gemini 3.5 Flash (Low)",     "name": "Gemini 3.5 Flash (Low)"},
            # Gemini 3.1 family
            {"id": "Gemini 3.1 Pro (High)",      "name": "Gemini 3.1 Pro (High)"},
            {"id": "Gemini 3.1 Pro (Low)",       "name": "Gemini 3.1 Pro (Low)"},
            {"id": "Gemini 3.1 Flash Lite",      "name": "Gemini 3.1 Flash Lite"},
            {"id": "Gemini 3.1 Flash Thinking",  "name": "Gemini 3.1 Flash Thinking"},
            {"id": "Gemini 3.1 Flash Image",     "name": "Gemini 3.1 Flash Image"},
            # Gemini 3 / 2.5
            {"id": "Gemini 3 Flash",             "name": "Gemini 3 Flash"},
            {"id": "Gemini 2.5 Pro",             "name": "Gemini 2.5 Pro"},
            # GPT-OSS
            {"id": "GPT-OSS 120B (Medium)",      "name": "GPT-OSS 120B (Medium)"},
            # Claude
            {"id": "Claude Sonnet 4.6 (Thinking)", "name": "Claude Sonnet 4.6 (Thinking)"},
            {"id": "Claude Opus 4.6 (Thinking)",   "name": "Claude Opus 4.6 (Thinking)"},
            # Image Generation
            {"id": "Image Generation (1:1)",     "name": "Image Generation (1:1)"},
        ],
    },

    # ─── Tier 1: Major Cloud Providers ────────────────────────────────────────
    "OpenAI": {
        "name": "OpenAI",
        "icon": "⊕",
        "color": "#10a37f",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "models": [
            {"id": "gpt-4.1",             "name": "GPT-4.1"},
            {"id": "gpt-4.1-mini",        "name": "GPT-4.1 Mini"},
            {"id": "gpt-4.1-nano",        "name": "GPT-4.1 Nano"},
            {"id": "o4-mini",             "name": "o4 Mini"},
            {"id": "o3",                  "name": "o3"},
            {"id": "o3-mini",             "name": "o3 Mini"},
            {"id": "o1",                  "name": "o1"},
            {"id": "gpt-4o",              "name": "GPT-4o"},
            {"id": "gpt-4o-mini",         "name": "GPT-4o Mini"},
        ],
    },
    "Anthropic": {
        "name": "Anthropic",
        "icon": "◈",
        "color": "#d97706",
        "base_url": "https://api.anthropic.com/v1",
        "api_key_env": "ANTHROPIC_API_KEY",
        "models": [
            {"id": "claude-fable-5",                "name": "Claude Fable 5"},
            {"id": "claude-opus-4-8",               "name": "Claude Opus 4.8"},
            {"id": "claude-sonnet-4-6",             "name": "Claude Sonnet 4.6"},
            {"id": "claude-haiku-4-5-20251001",     "name": "Claude Haiku 4.5"},
            {"id": "claude-3-5-sonnet-20241022",    "name": "Claude 3.5 Sonnet"},
            {"id": "claude-3-5-haiku-20241022",     "name": "Claude 3.5 Haiku"},
            {"id": "claude-3-opus-20240229",        "name": "Claude 3 Opus"},
        ],
    },
    "Gemini": {
        "name": "Google Gemini",
        "icon": "◉",
        "color": "#4285f4",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "api_key_env": "GOOGLE_API_KEY",
        "is_gemini": True,
        "models": [
            {"id": "gemini-2.5-pro",                    "name": "Gemini 2.5 Pro"},
            {"id": "gemini-2.5-flash",                  "name": "Gemini 2.5 Flash (Free)"},
            {"id": "gemini-2.5-flash-lite-preview-06-17","name": "Gemini 2.5 Flash Lite (Free)"},
            {"id": "gemini-2.0-flash",                  "name": "Gemini 2.0 Flash (Free)"},
            {"id": "gemini-2.0-flash-lite",             "name": "Gemini 2.0 Flash Lite (Free)"},
            {"id": "gemini-2.0-flash-exp",              "name": "Gemini 2.0 Flash Exp (Free)"},
            {"id": "gemini-1.5-pro",                    "name": "Gemini 1.5 Pro"},
            {"id": "gemini-1.5-flash",                  "name": "Gemini 1.5 Flash (Free)"},
            {"id": "gemini-1.5-flash-8b",               "name": "Gemini 1.5 Flash 8B (Free)"},
        ],
    },
    "xAI": {
        "name": "xAI (Grok)",
        "icon": "✕",
        "color": "#1da1f2",
        "base_url": "https://api.x.ai/v1",
        "api_key_env": "XAI_API_KEY",
        "models": [
            {"id": "grok-3",              "name": "Grok 3"},
            {"id": "grok-3-fast",         "name": "Grok 3 Fast"},
            {"id": "grok-3-mini",         "name": "Grok 3 Mini"},
            {"id": "grok-3-mini-fast",    "name": "Grok 3 Mini Fast"},
            {"id": "grok-2-1212",         "name": "Grok 2"},
            {"id": "grok-2-vision-1212",  "name": "Grok 2 Vision"},
        ],
    },

    # ─── Fast Inference (Free Tier) ───────────────────────────────────────────
    "Groq": {
        "name": "Groq",
        "icon": "▶",
        "color": "#f55036",
        "base_url": "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "models": [
            {"id": "meta-llama/llama-4-maverick-17b-128e-instruct", "name": "Llama 4 Maverick (Free)"},
            {"id": "meta-llama/llama-4-scout-17b-16e-instruct",     "name": "Llama 4 Scout (Free)"},
            {"id": "llama-3.3-70b-versatile",                       "name": "Llama 3.3 70B (Free)"},
            {"id": "llama-3.1-70b-versatile",                       "name": "Llama 3.1 70B (Free)"},
            {"id": "llama-3.1-8b-instant",                          "name": "Llama 3.1 8B Instant (Free)"},
            {"id": "deepseek-r1-distill-llama-70b",                 "name": "DeepSeek R1 Distill 70B (Free)"},
            {"id": "qwen-qwq-32b",                                  "name": "Qwen QwQ 32B (Free)"},
            {"id": "gemma2-9b-it",                                  "name": "Gemma 2 9B (Free)"},
            {"id": "compound-beta",                                  "name": "Compound Beta (Free)"},
            {"id": "mixtral-8x7b-32768",                            "name": "Mixtral 8x7B (Free)"},
        ],
    },
    "Cerebras": {
        "name": "Cerebras",
        "icon": "⬡",
        "color": "#ff6b35",
        "base_url": "https://api.cerebras.ai/v1",
        "api_key_env": "CEREBRAS_API_KEY",
        "models": [
            {"id": "llama-3.3-70b",   "name": "Llama 3.3 70B (Free)"},
            {"id": "llama3.1-70b",    "name": "Llama 3.1 70B (Free)"},
            {"id": "llama3.1-8b",     "name": "Llama 3.1 8B (Free)"},
            {"id": "qwen-3-32b",      "name": "Qwen 3 32B (Free)"},
        ],
    },
    "SambaNova": {
        "name": "SambaNova",
        "icon": "◤",
        "color": "#e11d48",
        "base_url": "https://api.sambanova.ai/v1",
        "api_key_env": "SAMBANOVA_API_KEY",
        "models": [
            {"id": "Meta-Llama-3.3-70B-Instruct",    "name": "Llama 3.3 70B (Free)"},
            {"id": "Meta-Llama-3.1-405B-Instruct",   "name": "Llama 3.1 405B (Free)"},
            {"id": "DeepSeek-R1",                    "name": "DeepSeek R1 (Free)"},
            {"id": "DeepSeek-V3-0324",               "name": "DeepSeek V3 (Free)"},
            {"id": "Qwen2.5-72B-Instruct",           "name": "Qwen 2.5 72B (Free)"},
            {"id": "Qwen2.5-Coder-32B-Instruct",     "name": "Qwen 2.5 Coder 32B (Free)"},
        ],
    },
    "ChutesAI": {
        "name": "Chutes AI",
        "icon": "⚡",
        "color": "#06b6d4",
        "base_url": "https://llm.chutes.ai/v1",
        "api_key_env": "CHUTES_API_KEY",
        "models": [
            {"id": "deepseek-ai/DeepSeek-R1",                   "name": "DeepSeek R1 (Free)"},
            {"id": "deepseek-ai/DeepSeek-V3-0324",              "name": "DeepSeek V3 (Free)"},
            {"id": "Qwen/Qwen3-235B-A22B",                      "name": "Qwen 3 235B (Free)"},
            {"id": "Qwen/Qwen3-30B-A3B",                        "name": "Qwen 3 30B (Free)"},
            {"id": "Qwen/Qwen3-32B",                            "name": "Qwen 3 32B (Free)"},
            {"id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", "name": "Llama 4 Maverick (Free)"},
            {"id": "meta-llama/Llama-4-Scout-17B-16E-Instruct", "name": "Llama 4 Scout (Free)"},
            {"id": "meta-llama/Llama-3.3-70B-Instruct",        "name": "Llama 3.3 70B (Free)"},
        ],
    },
    "GitHubModels": {
        "name": "GitHub Models",
        "icon": "⊛",
        "color": "#24292f",
        "base_url": "https://models.inference.ai.azure.com",
        "api_key_env": "GITHUB_TOKEN",
        "models": [
            {"id": "gpt-4o",                        "name": "GPT-4o (Free)"},
            {"id": "gpt-4o-mini",                   "name": "GPT-4o Mini (Free)"},
            {"id": "o1-mini",                       "name": "o1 Mini (Free)"},
            {"id": "o3-mini",                       "name": "o3 Mini (Free)"},
            {"id": "meta-llama/Llama-3.3-70B-Instruct",  "name": "Llama 3.3 70B (Free)"},
            {"id": "meta-llama/Llama-3.1-405B-Instruct", "name": "Llama 3.1 405B (Free)"},
            {"id": "Mistral-Large-2411",            "name": "Mistral Large (Free)"},
            {"id": "Mistral-small",                 "name": "Mistral Small (Free)"},
            {"id": "Phi-4",                         "name": "Phi 4 (Free)"},
            {"id": "Phi-3.5-MoE-instruct",          "name": "Phi 3.5 MoE (Free)"},
            {"id": "AI21-Jamba-1.5-Large",          "name": "Jamba 1.5 Large (Free)"},
            {"id": "DeepSeek-R1",                   "name": "DeepSeek R1 (Free)"},
            {"id": "DeepSeek-V3-0324",              "name": "DeepSeek V3 (Free)"},
        ],
    },

    # ─── OpenRouter (Gateway + Free Models) ───────────────────────────────────
    "OpenRouter": {
        "name": "OpenRouter",
        "icon": "◇",
        "color": "#a855f7",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "models": [
            # Free models (no payment needed, :free suffix)
            {"id": "deepseek/deepseek-r1:free",                          "name": "DeepSeek R1 (Free)"},
            {"id": "deepseek/deepseek-v3-0324:free",                     "name": "DeepSeek V3 (Free)"},
            {"id": "meta-llama/llama-4-maverick:free",                   "name": "Llama 4 Maverick (Free)"},
            {"id": "meta-llama/llama-4-scout:free",                      "name": "Llama 4 Scout (Free)"},
            {"id": "meta-llama/llama-3.3-70b-instruct:free",             "name": "Llama 3.3 70B (Free)"},
            {"id": "google/gemini-2.0-flash-exp:free",                   "name": "Gemini 2.0 Flash Exp (Free)"},
            {"id": "google/gemma-3-27b-it:free",                         "name": "Gemma 3 27B (Free)"},
            {"id": "microsoft/phi-4:free",                               "name": "Phi 4 (Free)"},
            {"id": "qwen/qwq-32b:free",                                  "name": "Qwen QwQ 32B (Free)"},
            {"id": "qwen/qwen3-235b-a22b:free",                          "name": "Qwen 3 235B (Free)"},
            {"id": "qwen/qwen3-30b-a3b:free",                            "name": "Qwen 3 30B (Free)"},
            {"id": "mistralai/mistral-small-3.1-24b-instruct:free",      "name": "Mistral Small 3.1 (Free)"},
            {"id": "moonshotai/moonlight-16b-a3b-instruct:free",         "name": "Moonlight 16B (Free)"},
            {"id": "thudm/glm-z1-32b:free",                              "name": "GLM Z1 32B (Free)"},
            # Paid models via OpenRouter
            {"id": "anthropic/claude-opus-4",                            "name": "Claude Opus 4"},
            {"id": "anthropic/claude-sonnet-4-5",                        "name": "Claude Sonnet 4.5"},
            {"id": "openai/gpt-4.1",                                     "name": "GPT-4.1"},
            {"id": "openai/o4-mini",                                     "name": "o4 Mini"},
            {"id": "google/gemini-2.5-pro",                              "name": "Gemini 2.5 Pro"},
            {"id": "x-ai/grok-3",                                        "name": "Grok 3"},
        ],
    },

    # ─── European / Specialized ────────────────────────────────────────────────
    "Mistral": {
        "name": "Mistral AI",
        "icon": "⊞",
        "color": "#ff7000",
        "base_url": "https://api.mistral.ai/v1",
        "api_key_env": "MISTRAL_API_KEY",
        "models": [
            {"id": "mistral-large-latest",              "name": "Mistral Large"},
            {"id": "mistral-medium-latest",             "name": "Mistral Medium"},
            {"id": "magistral-medium-2506",             "name": "Magistral Medium (Reasoning)"},
            {"id": "mistral-small-latest",              "name": "Mistral Small"},
            {"id": "mistral-small-3.1-24b-instruct",    "name": "Mistral Small 3.1 (Free)"},
            {"id": "codestral-latest",                  "name": "Codestral"},
            {"id": "pixtral-large-2411",                "name": "Pixtral Large (Vision)"},
            {"id": "open-mixtral-8x22b",                "name": "Mixtral 8x22B"},
        ],
    },
    "Cohere": {
        "name": "Cohere",
        "icon": "◍",
        "color": "#39594d",
        "base_url": "https://api.cohere.com/compatibility/v1",
        "api_key_env": "COHERE_API_KEY",
        "models": [
            {"id": "command-a-03-2025",      "name": "Command A"},
            {"id": "command-r-plus-08-2024", "name": "Command R+"},
            {"id": "command-r-08-2024",      "name": "Command R"},
            {"id": "command-r7b-12-2024",    "name": "Command R7B"},
        ],
    },
    "Perplexity": {
        "name": "Perplexity",
        "icon": "◌",
        "color": "#1fb8cd",
        "base_url": "https://api.perplexity.ai",
        "api_key_env": "PERPLEXITY_API_KEY",
        "models": [
            {"id": "sonar-pro",             "name": "Sonar Pro"},
            {"id": "sonar",                 "name": "Sonar"},
            {"id": "sonar-reasoning-pro",   "name": "Sonar Reasoning Pro"},
            {"id": "sonar-reasoning",       "name": "Sonar Reasoning"},
            {"id": "sonar-deep-research",   "name": "Sonar Deep Research"},
            {"id": "r1-1776",               "name": "R1-1776 (Reasoning)"},
        ],
    },

    # ─── DeepSeek ──────────────────────────────────────────────────────────────
    "DeepSeek": {
        "name": "DeepSeek",
        "icon": "◆",
        "color": "#4da3ff",
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
        "models": [
            {"id": "deepseek-chat",     "name": "DeepSeek V3 (Chat)"},
            {"id": "deepseek-reasoner", "name": "DeepSeek R1 (Reasoner)"},
        ],
    },

    # ─── Alternative Inference Platforms ──────────────────────────────────────
    "TogetherAI": {
        "name": "Together AI",
        "icon": "⧖",
        "color": "#7c3aed",
        "base_url": "https://api.together.xyz/v1",
        "api_key_env": "TOGETHER_API_KEY",
        "models": [
            {"id": "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", "name": "Llama 3.1 405B Turbo"},
            {"id": "meta-llama/Meta-Llama-3.3-70B-Instruct-Turbo",  "name": "Llama 3.3 70B Turbo"},
            {"id": "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",   "name": "Llama 3.1 8B Turbo"},
            {"id": "deepseek-ai/DeepSeek-R1",                       "name": "DeepSeek R1"},
            {"id": "deepseek-ai/DeepSeek-V3",                       "name": "DeepSeek V3"},
            {"id": "Qwen/Qwen2.5-72B-Instruct-Turbo",              "name": "Qwen 2.5 72B Turbo"},
            {"id": "Qwen/Qwen3-235B-A22B",                         "name": "Qwen 3 235B"},
        ],
    },
    "DeepInfra": {
        "name": "DeepInfra",
        "icon": "⬢",
        "color": "#6366f1",
        "base_url": "https://api.deepinfra.com/v1/openai",
        "api_key_env": "DEEPINFRA_API_KEY",
        "models": [
            {"id": "meta-llama/Meta-Llama-3.1-70B-Instruct",  "name": "Llama 3.1 70B"},
            {"id": "meta-llama/Llama-3.3-70B-Instruct-Turbo", "name": "Llama 3.3 70B Turbo"},
            {"id": "deepseek-ai/DeepSeek-R1",                 "name": "DeepSeek R1"},
            {"id": "deepseek-ai/DeepSeek-V3",                 "name": "DeepSeek V3"},
            {"id": "Qwen/Qwen3-235B-A22B",                    "name": "Qwen 3 235B"},
            {"id": "Qwen/Qwen2.5-72B-Instruct",               "name": "Qwen 2.5 72B"},
        ],
    },
    "FireworksAI": {
        "name": "Fireworks AI",
        "icon": "✦",
        "color": "#ef4444",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "api_key_env": "FIREWORKS_API_KEY",
        "models": [
            {"id": "accounts/fireworks/models/llama4-maverick-instruct-basic", "name": "Llama 4 Maverick"},
            {"id": "accounts/fireworks/models/llama4-scout-instruct-basic",    "name": "Llama 4 Scout"},
            {"id": "accounts/fireworks/models/llama-v3p3-70b-instruct",        "name": "Llama 3.3 70B"},
            {"id": "accounts/fireworks/models/deepseek-r1",                    "name": "DeepSeek R1"},
            {"id": "accounts/fireworks/models/deepseek-v3",                    "name": "DeepSeek V3"},
            {"id": "accounts/fireworks/models/qwen3-235b-a22b",               "name": "Qwen 3 235B"},
        ],
    },
    "Hyperbolic": {
        "name": "Hyperbolic",
        "icon": "≋",
        "color": "#0ea5e9",
        "base_url": "https://api.hyperbolic.xyz/v1",
        "api_key_env": "HYPERBOLIC_API_KEY",
        "models": [
            {"id": "meta-llama/Llama-3.3-70B-Instruct",      "name": "Llama 3.3 70B"},
            {"id": "meta-llama/Meta-Llama-3.1-405B-Instruct", "name": "Llama 3.1 405B"},
            {"id": "deepseek-ai/DeepSeek-R1",                 "name": "DeepSeek R1"},
            {"id": "deepseek-ai/DeepSeek-V3",                 "name": "DeepSeek V3"},
            {"id": "Qwen/Qwen3-235B-A22B",                    "name": "Qwen 3 235B"},
            {"id": "Qwen/Qwen2.5-72B-Instruct",               "name": "Qwen 2.5 72B"},
        ],
    },
    "NovitaAI": {
        "name": "Novita AI",
        "icon": "⬛",
        "color": "#8b5cf6",
        "base_url": "https://api.novita.ai/v3/openai",
        "api_key_env": "NOVITA_API_KEY",
        "models": [
            {"id": "deepseek/deepseek-r1",                    "name": "DeepSeek R1"},
            {"id": "deepseek/deepseek-v3-0324",               "name": "DeepSeek V3"},
            {"id": "meta-llama/llama-3.3-70b-instruct",       "name": "Llama 3.3 70B"},
            {"id": "qwen/qwen3-235b-a22b",                    "name": "Qwen 3 235B"},
            {"id": "qwen/qwen2.5-72b-instruct",               "name": "Qwen 2.5 72B"},
        ],
    },

    # ─── NVIDIA NIM ────────────────────────────────────────────────────────────
    "NVIDIA": {
        "name": "NVIDIA NIM",
        "icon": "▰",
        "color": "#76b900",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "api_key_env": "NVIDIA_API_KEY",
        "models": [
            {"id": "meta/llama-4-maverick-17b-128e-instruct",         "name": "Llama 4 Maverick"},
            {"id": "meta/llama-4-scout-17b-16e-instruct",             "name": "Llama 4 Scout"},
            {"id": "meta/llama-3.1-405b-instruct",                    "name": "Llama 3.1 405B"},
            {"id": "nvidia/llama-3.1-nemotron-70b-instruct",          "name": "Nemotron 70B"},
            {"id": "deepseek-ai/deepseek-r1",                         "name": "DeepSeek R1"},
            {"id": "qwen/qwen3-235b-a22b",                            "name": "Qwen 3 235B"},
            {"id": "qwen/qwen2.5-72b-instruct",                       "name": "Qwen 2.5 72B"},
        ],
    },

    # ─── Chinese / Asian Providers ─────────────────────────────────────────────
    "MoonshotAI": {
        "name": "Moonshot AI (Kimi)",
        "icon": "☾",
        "color": "#4f46e5",
        "base_url": "https://api.moonshot.cn/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "models": [
            {"id": "moonshot-v1-128k", "name": "Moonshot 128K"},
            {"id": "moonshot-v1-32k",  "name": "Moonshot 32K"},
            {"id": "moonshot-v1-8k",   "name": "Moonshot 8K"},
            {"id": "kimi-latest",      "name": "Kimi Latest"},
        ],
    },
    "ZhipuAI": {
        "name": "Zhipu AI (GLM)",
        "icon": "⬡",
        "color": "#3b82f6",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "api_key_env": "ZHIPUAI_API_KEY",
        "models": [
            {"id": "glm-4-plus",  "name": "GLM-4 Plus"},
            {"id": "glm-4",       "name": "GLM-4"},
            {"id": "glm-4-flash", "name": "GLM-4 Flash (Free)"},
            {"id": "glm-z1-plus", "name": "GLM-Z1 Plus (Reasoning)"},
            {"id": "glm-z1-flash","name": "GLM-Z1 Flash (Free)"},
        ],
    },
    "Minimax": {
        "name": "MiniMax",
        "icon": "◎",
        "color": "#7c3aed",
        "base_url": "https://api.minimaxi.chat/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models": [
            {"id": "MiniMax-Text-01", "name": "MiniMax Text 01"},
            {"id": "abab6.5s-chat",   "name": "ABAB 6.5S"},
        ],
    },
    "AlibabaDashScope": {
        "name": "Alibaba (Qwen)",
        "icon": "◈",
        "color": "#f97316",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models": [
            {"id": "qwen-max",               "name": "Qwen Max"},
            {"id": "qwen-plus",              "name": "Qwen Plus"},
            {"id": "qwen-turbo",             "name": "Qwen Turbo"},
            {"id": "qwen3-235b-a22b",        "name": "Qwen 3 235B"},
            {"id": "qwen3-32b",              "name": "Qwen 3 32B"},
            {"id": "qwen2.5-72b-instruct",   "name": "Qwen 2.5 72B"},
            {"id": "qwq-32b",                "name": "QwQ 32B (Reasoning)"},
        ],
    },

    # ─── Enterprise / Specialized ──────────────────────────────────────────────
    "AzureOpenAI": {
        "name": "Azure OpenAI",
        "icon": "⊞",
        "color": "#0078d4",
        "base_url": "",
        "api_key_env": "AZURE_OPENAI_API_KEY",
        "requires_base_url": True,
        "models": [
            {"id": "gpt-4.1",       "name": "GPT-4.1"},
            {"id": "gpt-4.1-mini",  "name": "GPT-4.1 Mini"},
            {"id": "gpt-4o",        "name": "GPT-4o"},
            {"id": "gpt-4o-mini",   "name": "GPT-4o Mini"},
            {"id": "o4-mini",       "name": "o4 Mini"},
            {"id": "o3",            "name": "o3"},
        ],
    },
    "UpstageAI": {
        "name": "Upstage AI",
        "icon": "↑",
        "color": "#6366f1",
        "base_url": "https://api.upstage.ai/v1",
        "api_key_env": "UPSTAGE_API_KEY",
        "models": [
            {"id": "solar-pro",  "name": "Solar Pro"},
            {"id": "solar-mini", "name": "Solar Mini"},
        ],
    },
    "VeniceAI": {
        "name": "Venice AI",
        "icon": "⛵",
        "color": "#0891b2",
        "base_url": "https://api.venice.ai/api/v1",
        "api_key_env": "VENICE_API_KEY",
        "models": [
            {"id": "llama-3.3-70b",              "name": "Llama 3.3 70B"},
            {"id": "deepseek-r1-671b",           "name": "DeepSeek R1"},
            {"id": "qwen3-235b",                 "name": "Qwen 3 235B"},
            {"id": "mistral-31-24b",             "name": "Mistral 3.1 24B"},
        ],
    },
    "CloudflareAI": {
        "name": "Cloudflare Workers AI",
        "icon": "☁",
        "color": "#f6821f",
        "base_url": "",
        "api_key_env": "CLOUDFLARE_API_TOKEN",
        "requires_base_url": True,
        "models": [
            {"id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast", "name": "Llama 3.3 70B (Free)"},
            {"id": "@cf/meta/llama-3.1-70b-instruct",          "name": "Llama 3.1 70B (Free)"},
            {"id": "@cf/meta/llama-3.1-8b-instruct",           "name": "Llama 3.1 8B (Free)"},
            {"id": "@cf/deepseek-ai/deepseek-r1",              "name": "DeepSeek R1 (Free)"},
            {"id": "@cf/qwen/qwen2.5-coder-32b-instruct",      "name": "Qwen 2.5 Coder (Free)"},
            {"id": "@cf/mistral/mistral-7b-instruct-v0.2",     "name": "Mistral 7B (Free)"},
        ],
    },

    # ─── Local / Self-hosted ───────────────────────────────────────────────────
    "Ollama": {
        "name": "Ollama (Local)",
        "icon": "⊙",
        "color": "#6b7280",
        "base_url": "http://localhost:11434/v1",
        "api_key_env": "",
        "is_local": True,
        "models": [
            {"id": "llama3.2",          "name": "Llama 3.2"},
            {"id": "llama3.1",          "name": "Llama 3.1"},
            {"id": "llama4",            "name": "Llama 4 Scout"},
            {"id": "qwen3",             "name": "Qwen 3"},
            {"id": "qwen2.5-coder",     "name": "Qwen 2.5 Coder"},
            {"id": "deepseek-r1",       "name": "DeepSeek R1"},
            {"id": "deepseek-v3",       "name": "DeepSeek V3"},
            {"id": "mistral",           "name": "Mistral"},
            {"id": "codellama",         "name": "Code Llama"},
            {"id": "phi4",              "name": "Phi 4"},
            {"id": "gemma3",            "name": "Gemma 3"},
        ],
    },
    "LMStudio": {
        "name": "LM Studio (Local)",
        "icon": "⊡",
        "color": "#6b7280",
        "base_url": "http://localhost:1234/v1",
        "api_key_env": "",
        "is_local": True,
        "models": [
            {"id": "local-model", "name": "Local Model"},
        ],
    },
    "OpenAICompatible": {
        "name": "Custom OpenAI-Compatible",
        "icon": "⬡",
        "color": "#64748b",
        "base_url": "",
        "api_key_env": "",
        "requires_base_url": True,
        "models": [
            {"id": "custom-model", "name": "Custom Model"},
        ],
    },
}
