"""Central provider registry for Dardcor Code.

Each entry defines display metadata, base_url, and a curated model list.
All non-Antigravity providers use StandardOpenAIProvider (OpenAI-compatible API).
Models marked with (Free) work without payment on the provider's free tier.
"""

from dardcor_agent.models.providers.opencode_zen_models import OPENCODE_ZEN_FREE_MODELS

PROVIDER_REGISTRY = {
    "Dardcor": {
        "name": "Dardcor",
        "icon": "D",
        "color": "#0e639c",
        "base_url": "",
        "api_key_env": "",
        "is_special": True,
        "built_in": True,
        "tier": "Built-in",
        "models": [
            {
                "id": "dardcor-v1",
                "name": "Dardcor v1",
                "description": "Virtual orchestrator that routes to configured free/provider models.",
            },
        ],
    },

    # ─── Special / OAuth-gated ─────────────────────────────────────────────────
    "Antigravity": {
        "name": "Antigravity",
        "icon": "✦",
        "color": "#8b5cf6",
        "base_url": "",
        "api_key_env": "",
        "is_special": True,
        "models": [
            # Gemini 3.5 Flash family
            {"id": "Gemini 3.5 Flash (High)",    "name": "Gemini 3.5 Flash (High)"},
            {"id": "Gemini 3.5 Flash (Medium)",  "name": "Gemini 3.5 Flash (Medium)"},
            {"id": "Gemini 3.5 Flash (Low)",     "name": "Gemini 3.5 Flash (Low)"},
            # Gemini 3.1 family
            {"id": "Gemini 3.1 Pro (High)",      "name": "Gemini 3.1 Pro (High)"},
            {"id": "Gemini 3.1 Pro (Low)",       "name": "Gemini 3.1 Pro (Low)"},
            {"id": "Gemini 3.1 Flash Lite",      "name": "Gemini 3.1 Flash Lite"},
            {"id": "Gemini 3.1 Flash Thinking",  "name": "Gemini 3.1 Flash Thinking"},
            {"id": "Gemini 3.1 Flash Image",     "name": "Gemini 3.1 Flash Image"},
            # Gemini 3 / 2.5
            {"id": "Gemini 3 Flash",             "name": "Gemini 3 Flash"},
            {"id": "Gemini 2.5 Pro",             "name": "Gemini 2.5 Pro"},
            # GPT-OSS
            {"id": "GPT-OSS 120B (Medium)",      "name": "GPT-OSS 120B (Medium)"},
            # Claude
            {"id": "Claude Sonnet 4.6 (Thinking)", "name": "Claude Sonnet 4.6 (Thinking)"},
            {"id": "Claude Opus 4.6 (Thinking)",   "name": "Claude Opus 4.6 (Thinking)"},
            # Image Generation
            {"id": "Image Generation (1:1)",     "name": "Image Generation (1:1)"},
        ],
    },

    # ─── Subscription Quota via Direct OAuth ──────────────────────────────────
    "ClaudeCodeSubscription": {
        "name": "Claude Pro/Max (OAuth)",
        "icon": "C",
        "color": "#d97706",
        "base_url": "https://api.anthropic.com/v1",
        "api_key_env": "CLAUDE_CODE_OAUTH_TOKEN",
        "tier": "Subscription",
        "oauth_provider": "claude",
        "auth_help": "Dardcor starts a local callback server, opens Claude OAuth, then stores the returned token locally.",
        "supports_web_login": True,
        "models": [
            {"id": "claude-code/claude-opus-4-8",     "name": "Claude Opus 4.8"},
            {"id": "claude-code/claude-sonnet-5",     "name": "Claude Sonnet 5"},
            {"id": "claude-code/claude-opus-4-7",     "name": "Claude Opus 4.7"},
            {"id": "claude-code/claude-sonnet-4-6",   "name": "Claude Sonnet 4.6"},
            {"id": "claude-code/claude-haiku-4-5",    "name": "Claude Haiku 4.5"},
        ],
    },
    "CodexSubscription": {
        "name": "ChatGPT Plus/Pro Codex (OAuth)",
        "icon": "⊕",
        "color": "#10a37f",
        "base_url": "https://chatgpt.com/backend-api/codex",
        "api_key_env": "CODEX_OAUTH_TOKEN",
        "tier": "Subscription",
        "oauth_provider": "codex",
        "auth_help": "Dardcor starts a local callback server on port 1455, opens OpenAI Codex OAuth, then stores the returned token locally.",
        "supports_web_login": True,
        "models": [
            {"id": "codex/gpt-5.5",             "name": "GPT-5.5"},
            {"id": "codex/gpt-5.4",             "name": "GPT-5.4"},
            {"id": "codex/gpt-5.3-codex",       "name": "GPT-5.3 Codex"},
            {"id": "codex/gpt-5.2-codex",       "name": "GPT-5.2 Codex"},
            {"id": "codex/gpt-5.1-codex-max",   "name": "GPT-5.1 Codex Max"},
        ],
    },

    # ─── Tier 1: Major Cloud Providers ────────────────────────────────────────
    "OpenAI": {
        "name": "OpenAI",
        "icon": "⊕",
        "color": "#10a37f",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "auth_url": "https://platform.openai.com/api-keys",
        "models_fetch_url": "https://api.openai.com/v1/models",
        "models": [
            {"id": "gpt-5.6-sol",         "name": "GPT-5.6 Sol (Preview, gated)"},
            {"id": "gpt-5.6-terra",       "name": "GPT-5.6 Terra (Preview, gated)"},
            {"id": "gpt-5.6-luna",        "name": "GPT-5.6 Luna (Preview, gated)"},
            {"id": "gpt-5.5",             "name": "GPT-5.5"},
            {"id": "gpt-5.5-2026-04-23",  "name": "GPT-5.5 Snapshot"},
            {"id": "gpt-5.4",             "name": "GPT-5.4"},
            {"id": "gpt-5.4-mini",        "name": "GPT-5.4 Mini"},
            {"id": "gpt-5",               "name": "GPT-5"},
            {"id": "gpt-5-mini",          "name": "GPT-5 Mini"},
            {"id": "gpt-5-nano",          "name": "GPT-5 Nano"},
            {"id": "gpt-4.1",             "name": "GPT-4.1"},
            {"id": "gpt-4o",              "name": "GPT-4o"},
        ],
    },
    "Anthropic": {
        "name": "Anthropic",
        "icon": "◈",
        "color": "#d97706",
        "base_url": "https://api.anthropic.com/v1",
        "api_key_env": "ANTHROPIC_API_KEY",
        "auth_url": "https://console.anthropic.com/settings/keys",
        "models": [
            {"id": "claude-fable-5",                "name": "Claude Fable 5 (Frontier)"},
            {"id": "claude-mythos-5",               "name": "Claude Mythos 5 (Project Glasswing)"},
            {"id": "claude-opus-4-8",               "name": "Claude Opus 4.8"},
            {"id": "claude-sonnet-5",               "name": "Claude Sonnet 5"},
            {"id": "claude-opus-4-7",               "name": "Claude Opus 4.7"},
            {"id": "claude-opus-4-6",               "name": "Claude Opus 4.6"},
            {"id": "claude-sonnet-4-6",             "name": "Claude Sonnet 4.6"},
            {"id": "claude-haiku-4-5",              "name": "Claude Haiku 4.5"},
            {"id": "claude-3-5-sonnet-20241022",    "name": "Claude 3.5 Sonnet (Legacy)"},
        ],
    },
    "Gemini": {
        "name": "Google Gemini",
        "icon": "◉",
        "color": "#4285f4",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "api_key_env": "GOOGLE_API_KEY",
        "is_gemini": True,
        "auth_url": "https://aistudio.google.com/apikey",
        "supports_web_login": True,
        "models_fetch_url": "https://generativelanguage.googleapis.com/v1beta/models",
        "models": [
            # Stable rolling aliases — always resolve for any key (put first).
            {"id": "gemini-flash-latest",           "name": "Gemini Flash (Latest, Free)"},
            {"id": "gemini-flash-lite-latest",      "name": "Gemini Flash Lite (Latest, Free)"},
            {"id": "gemini-3.5-flash",              "name": "Gemini 3.5 Flash"},
            {"id": "gemini-3.1-pro-preview",        "name": "Gemini 3.1 Pro"},
            {"id": "gemini-3.1-flash-lite",         "name": "Gemini 3.1 Flash Lite (Free)"},
            {"id": "gemini-3.1-flash-image",        "name": "Gemini 3.1 Flash Image"},
            {"id": "gemini-3-pro-image",            "name": "Gemini 3 Pro Image"},
            {"id": "gemini-3-flash-preview",        "name": "Gemini 3 Flash (Preview)"},
        ],
    },
    "xAI": {
        "name": "xAI (Grok)",
        "icon": "✕",
        "color": "#1da1f2",
        "base_url": "https://api.x.ai/v1",
        "api_key_env": "XAI_API_KEY",
        "auth_url": "https://console.x.ai",
        "supports_web_login": True,
        "models_fetch_url": "https://api.x.ai/v1/models",
        "models": [
            {"id": "grok-4.3",                     "name": "Grok 4.3"},
            {"id": "grok-4.20-0309-reasoning",     "name": "Grok 4.20 Reasoning"},
            {"id": "grok-4.20-0309-non-reasoning", "name": "Grok 4.20 Non-Reasoning"},
            {"id": "grok-4.20-multi-agent-0309",   "name": "Grok 4.20 Multi-Agent"},
            {"id": "grok-build-0.1",               "name": "Grok Build 0.1"},
        ],
    },

    # ─── Fast Inference (Free Tier) ───────────────────────────────────────────
    "Groq": {
        "name": "Groq",
        "icon": "▶",
        "color": "#f55036",
        "base_url": "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "models_fetch_url": "https://api.groq.com/openai/v1/models",
        "auth_url": "https://console.groq.com/keys",
        "supports_web_login": True,
        "models": [
            {"id": "llama-3.3-70b-versatile",                       "name": "Llama 3.3 70B (Free)"},
            {"id": "llama-3.1-8b-instant",                          "name": "Llama 3.1 8B Instant (Free)"},
            {"id": "openai/gpt-oss-120b",                           "name": "GPT OSS 120B"},
            {"id": "openai/gpt-oss-20b",                            "name": "GPT OSS 20B"},
            {"id": "qwen/qwen3-32b",                                "name": "Qwen 3 32B"},
            {"id": "whisper-large-v3",                              "name": "Whisper Large V3"},
            {"id": "whisper-large-v3-turbo",                        "name": "Whisper Large V3 Turbo"},
        ],
    },
    "Cerebras": {
        "name": "Cerebras",
        "icon": "⬡",
        "color": "#ff6b35",
        "base_url": "https://api.cerebras.ai/v1",
        "api_key_env": "CEREBRAS_API_KEY",
        "models": [
            {"id": "llama-3.3-70b",   "name": "Llama 3.3 70B (Free)"},
            {"id": "llama3.1-70b",    "name": "Llama 3.1 70B (Free)"},
            {"id": "llama3.1-8b",     "name": "Llama 3.1 8B (Free)"},
            {"id": "qwen-3-32b",      "name": "Qwen 3 32B (Free)"},
        ],
    },
    "SambaNova": {
        "name": "SambaNova",
        "icon": "◤",
        "color": "#e11d48",
        "base_url": "https://api.sambanova.ai/v1",
        "api_key_env": "SAMBANOVA_API_KEY",
        "models": [
            {"id": "Meta-Llama-3.3-70B-Instruct",    "name": "Llama 3.3 70B (Free)"},
            {"id": "Meta-Llama-3.1-405B-Instruct",   "name": "Llama 3.1 405B (Free)"},
            {"id": "DeepSeek-R1",                    "name": "DeepSeek R1 (Free)"},
            {"id": "DeepSeek-V3-0324",               "name": "DeepSeek V3 (Free)"},
            {"id": "Qwen2.5-72B-Instruct",           "name": "Qwen 2.5 72B (Free)"},
            {"id": "Qwen2.5-Coder-32B-Instruct",     "name": "Qwen 2.5 Coder 32B (Free)"},
        ],
    },
    "ChutesAI": {
        "name": "Chutes AI",
        "icon": "⚡",
        "color": "#06b6d4",
        "base_url": "https://llm.chutes.ai/v1",
        "api_key_env": "CHUTES_API_KEY",
        "models": [
            {"id": "deepseek-ai/DeepSeek-R1",                   "name": "DeepSeek R1 (Free)"},
            {"id": "deepseek-ai/DeepSeek-V3-0324",              "name": "DeepSeek V3 (Free)"},
            {"id": "Qwen/Qwen3-235B-A22B",                      "name": "Qwen 3 235B (Free)"},
            {"id": "Qwen/Qwen3-30B-A3B",                        "name": "Qwen 3 30B (Free)"},
            {"id": "Qwen/Qwen3-32B",                            "name": "Qwen 3 32B (Free)"},
            {"id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", "name": "Llama 4 Maverick (Free)"},
            {"id": "meta-llama/Llama-4-Scout-17B-16E-Instruct", "name": "Llama 4 Scout (Free)"},
            {"id": "meta-llama/Llama-3.3-70B-Instruct",        "name": "Llama 3.3 70B (Free)"},
        ],
    },
    "GitHubModels": {
        "name": "GitHub Models",
        "icon": "⊛",
        "color": "#24292f",
        "base_url": "https://models.inference.ai.azure.com",
        "api_key_env": "GITHUB_TOKEN",
        "models": [
            {"id": "gpt-4o",                        "name": "GPT-4o (Free)"},
            {"id": "gpt-4o-mini",                   "name": "GPT-4o Mini (Free)"},
            {"id": "o1-mini",                       "name": "o1 Mini (Free)"},
            {"id": "o3-mini",                       "name": "o3 Mini (Free)"},
            {"id": "meta-llama/Llama-3.3-70B-Instruct",  "name": "Llama 3.3 70B (Free)"},
            {"id": "meta-llama/Llama-3.1-405B-Instruct", "name": "Llama 3.1 405B (Free)"},
            {"id": "Mistral-Large-2411",            "name": "Mistral Large (Free)"},
            {"id": "Mistral-small",                 "name": "Mistral Small (Free)"},
            {"id": "Phi-4",                         "name": "Phi 4 (Free)"},
            {"id": "Phi-3.5-MoE-instruct",          "name": "Phi 3.5 MoE (Free)"},
            {"id": "AI21-Jamba-1.5-Large",          "name": "Jamba 1.5 Large (Free)"},
            {"id": "DeepSeek-R1",                   "name": "DeepSeek R1 (Free)"},
            {"id": "DeepSeek-V3-0324",              "name": "DeepSeek V3 (Free)"},
        ],
    },

    # ─── OpenRouter (Gateway + Free Models) ───────────────────────────────────
    "OpenRouter": {
        "name": "OpenRouter",
        "icon": "◇",
        "color": "#a855f7",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "models_fetch_url": "https://openrouter.ai/api/v1/models",
        "auth_url": "https://openrouter.ai/keys",
        "supports_web_login": True,
        "models": [
            {"id": "openrouter/free",                                  "name": "Auto Free Router", "free": True},
            {"id": "openrouter/auto",                                  "name": "Auto Best Model"},
            # Free models (:free suffix)
            {"id": "deepseek/deepseek-r1:free",                        "name": "DeepSeek R1 (Free)", "free": True},
            {"id": "deepseek/deepseek-v3-0324:free",                     "name": "DeepSeek V3 (Free)", "free": True},
            {"id": "deepseek/deepseek-chat-v3-0324:free",                "name": "DeepSeek Chat V3 (Free)", "free": True},
            {"id": "meta-llama/llama-4-maverick:free",                   "name": "Llama 4 Maverick (Free)", "free": True},
            {"id": "meta-llama/llama-4-scout:free",                      "name": "Llama 4 Scout (Free)", "free": True},
            {"id": "meta-llama/llama-3.3-70b-instruct:free",             "name": "Llama 3.3 70B (Free)", "free": True},
            {"id": "meta-llama/llama-3.1-8b-instruct:free",              "name": "Llama 3.1 8B (Free)", "free": True},
            {"id": "google/gemini-2.0-flash-exp:free",                   "name": "Gemini 2.0 Flash Exp (Free)", "free": True},
            {"id": "google/gemma-3-27b-it:free",                         "name": "Gemma 3 27B (Free)", "free": True},
            {"id": "google/gemma-3-12b-it:free",                         "name": "Gemma 3 12B (Free)", "free": True},
            {"id": "microsoft/phi-4:free",                               "name": "Phi 4 (Free)", "free": True},
            {"id": "qwen/qwq-32b:free",                                  "name": "Qwen QwQ 32B (Free)", "free": True},
            {"id": "qwen/qwen3-235b-a22b:free",                          "name": "Qwen 3 235B (Free)", "free": True},
            {"id": "qwen/qwen3-30b-a3b:free",                            "name": "Qwen 3 30B (Free)", "free": True},
            {"id": "qwen/qwen3-32b:free",                                "name": "Qwen 3 32B (Free)", "free": True},
            {"id": "mistralai/mistral-small-3.1-24b-instruct:free",      "name": "Mistral Small 3.1 (Free)", "free": True},
            {"id": "moonshotai/moonlight-16b-a3b-instruct:free",         "name": "Moonlight 16B (Free)", "free": True},
            {"id": "thudm/glm-z1-32b:free",                              "name": "GLM Z1 32B (Free)", "free": True},
            {"id": "x-ai/grok-3-mini-beta:free",                         "name": "Grok 3 Mini Beta (Free)", "free": True},
            {"id": "zhipu-ai/glm-4-32b:free",                            "name": "GLM 4 32B (Free)", "free": True},
            {"id": "nousresearch/hermes-3-llama-3.1-70b:free",           "name": "Hermes 3 Llama 70B (Free)", "free": True},
            {"id": "nvidia/nemotron-3-nano-30b-a3b:free",                "name": "Nemotron 3 Nano 30B (Free)", "free": True},
            # Paid frontier 2026
            {"id": "openai/gpt-5.5",                                     "name": "GPT 5.5"},
            {"id": "openai/gpt-5.5-pro",                                 "name": "GPT 5.5 Pro"},
            {"id": "openai/gpt-5.4-mini",                                "name": "GPT 5.4 Mini"},
            {"id": "anthropic/claude-fable-5",                           "name": "Claude Fable 5"},
            {"id": "anthropic/claude-opus-4-8",                          "name": "Claude Opus 4.8"},
            {"id": "anthropic/claude-sonnet-5",                          "name": "Claude Sonnet 5"},
            {"id": "google/gemini-3.5-flash",                            "name": "Gemini 3.5 Flash"},
            {"id": "google/gemini-3.1-pro-preview",                      "name": "Gemini 3.1 Pro"},
            {"id": "x-ai/grok-3",                                        "name": "Grok 3"},
            {"id": "deepseek/deepseek-v4-flash",                         "name": "DeepSeek V4 Flash"},
        ],
    },

    # ─── European / Specialized ────────────────────────────────────────────────
    "Mistral": {
        "name": "Mistral AI",
        "icon": "⊞",
        "color": "#ff7000",
        "base_url": "https://api.mistral.ai/v1",
        "api_key_env": "MISTRAL_API_KEY",
        "auth_url": "https://console.mistral.ai/api-keys",
        "supports_web_login": True,
        "models_fetch_url": "https://api.mistral.ai/v1/models",
        "models": [
            {"id": "mistral-large-latest",              "name": "Mistral Large"},
            {"id": "mistral-medium-latest",             "name": "Mistral Medium"},
            {"id": "mistral-small-latest",              "name": "Mistral Small"},
            {"id": "magistral-medium-latest",           "name": "Magistral Medium"},
            {"id": "codestral-latest",                  "name": "Codestral"},
            {"id": "devstral-latest",                   "name": "Devstral"},
            {"id": "devstral-medium-latest",            "name": "Devstral Medium"},
            {"id": "ministral-14b-latest",              "name": "Ministral 14B"},
            {"id": "ministral-8b-latest",               "name": "Ministral 8B"},
            {"id": "ministral-3b-latest",               "name": "Ministral 3B"},
        ],
    },
    "Cohere": {
        "name": "Cohere",
        "icon": "◍",
        "color": "#39594d",
        "base_url": "https://api.cohere.com/compatibility/v1",
        "api_key_env": "COHERE_API_KEY",
        "models": [
            {"id": "command-a-plus-05-2026", "name": "Command A+"},
            {"id": "command-a-03-2025",      "name": "Command A"},
            {"id": "command-r7b-12-2024",    "name": "Command R7B"},
            {"id": "command-r-plus-08-2024", "name": "Command R+"},
        ],
    },
    "Perplexity": {
        "name": "Perplexity",
        "icon": "◌",
        "color": "#1fb8cd",
        "base_url": "https://api.perplexity.ai/v1/sonar",
        "api_key_env": "PERPLEXITY_API_KEY",
        "single_endpoint": True,
        "models": [
            {"id": "sonar",                 "name": "Sonar"},
            {"id": "sonar-pro",             "name": "Sonar Pro"},
            {"id": "sonar-deep-research",   "name": "Sonar Deep Research"},
            {"id": "sonar-reasoning-pro",   "name": "Sonar Reasoning Pro"},
        ],
    },

    # ─── DeepSeek ──────────────────────────────────────────────────────────────
    "DeepSeek": {
        "name": "DeepSeek",
        "icon": "◆",
        "color": "#4da3ff",
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
        "auth_url": "https://platform.deepseek.com/api_keys",
        "supports_web_login": True,
        "models": [
            {"id": "deepseek-v4-pro",      "name": "DeepSeek V4 Pro"},
            {"id": "deepseek-v4-flash",    "name": "DeepSeek V4 Flash"},
        ],
    },

    # ─── Alternative Inference Platforms ──────────────────────────────────────
    "TogetherAI": {
        "name": "Together AI",
        "icon": "⧖",
        "color": "#7c3aed",
        "base_url": "https://api.together.xyz/v1",
        "api_key_env": "TOGETHER_API_KEY",
        "models_fetch_url": "https://api.together.xyz/v1/models",
        "models": [
            {"id": "meta-llama/Meta-Llama-3.3-70B-Instruct-Turbo",  "name": "Llama 3.3 70B Turbo"},
            {"id": "deepseek-ai/DeepSeek-V4-Pro",                   "name": "DeepSeek V4 Pro"},
            {"id": "deepseek-ai/DeepSeek-V3.1",                     "name": "DeepSeek V3.1"},
            {"id": "deepseek-ai/DeepSeek-R1",                       "name": "DeepSeek R1"},
            {"id": "Qwen/Qwen3.7-Max",                              "name": "Qwen 3.7 Max"},
            {"id": "Qwen/Qwen3.7-Plus",                             "name": "Qwen 3.7 Plus"},
            {"id": "Qwen/Qwen3.5-9B",                               "name": "Qwen 3.5 9B"},
            {"id": "MiniMaxAI/MiniMax-M3",                          "name": "MiniMax M3"},
        ],
    },
    "DeepInfra": {
        "name": "DeepInfra",
        "icon": "⬢",
        "color": "#6366f1",
        "base_url": "https://api.deepinfra.com/v1/openai",
        "api_key_env": "DEEPINFRA_API_KEY",
        "models_fetch_url": "https://api.deepinfra.com/models/list",
        "models": [
            {"id": "Qwen/Qwen3-Max",                          "name": "Qwen 3 Max"},
            {"id": "Qwen/Qwen3-Max-Thinking",                 "name": "Qwen 3 Max Thinking"},
            {"id": "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo", "name": "Qwen 3 Coder 480B"},
            {"id": "deepseek-ai/DeepSeek-V3-0324",            "name": "DeepSeek V3 0324"},
            {"id": "deepseek-ai/DeepSeek-V3",                 "name": "DeepSeek V3"},
            {"id": "Qwen/Qwen3-32B",                          "name": "Qwen 3 32B"},
        ],
    },
    "FireworksAI": {
        "name": "Fireworks AI",
        "icon": "✦",
        "color": "#ef4444",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "api_key_env": "FIREWORKS_API_KEY",
        "models": [
            {"id": "accounts/fireworks/models/deepseek-v4-pro",                "name": "DeepSeek V4 Pro"},
            {"id": "accounts/fireworks/models/deepseek-v4-flash",              "name": "DeepSeek V4 Flash"},
            {"id": "accounts/fireworks/models/deepseek-v3p1",                  "name": "DeepSeek V3.1"},
            {"id": "accounts/fireworks/models/llama4-maverick-instruct-basic", "name": "Llama 4 Maverick"},
            {"id": "accounts/fireworks/models/llama4-scout-instruct-basic",    "name": "Llama 4 Scout"},
            {"id": "accounts/fireworks/models/deepseek-r1",                    "name": "DeepSeek R1"},
            {"id": "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct", "name": "Qwen 3 Coder 480B"},
        ],
    },
    "Hyperbolic": {
        "name": "Hyperbolic",
        "icon": "≋",
        "color": "#0ea5e9",
        "base_url": "https://api.hyperbolic.xyz/v1",
        "api_key_env": "HYPERBOLIC_API_KEY",
        "models": [
            {"id": "meta-llama/Llama-3.3-70B-Instruct",      "name": "Llama 3.3 70B"},
            {"id": "meta-llama/Meta-Llama-3.1-405B-Instruct", "name": "Llama 3.1 405B"},
            {"id": "deepseek-ai/DeepSeek-R1",                 "name": "DeepSeek R1"},
            {"id": "deepseek-ai/DeepSeek-V3",                 "name": "DeepSeek V3"},
            {"id": "Qwen/Qwen3-235B-A22B",                    "name": "Qwen 3 235B"},
            {"id": "Qwen/Qwen2.5-72B-Instruct",               "name": "Qwen 2.5 72B"},
        ],
    },
    "NovitaAI": {
        "name": "Novita AI",
        "icon": "⬛",
        "color": "#8b5cf6",
        "base_url": "https://api.novita.ai/v3/openai",
        "api_key_env": "NOVITA_API_KEY",
        "models": [
            {"id": "deepseek/deepseek-r1",                    "name": "DeepSeek R1"},
            {"id": "deepseek/deepseek-v3-0324",               "name": "DeepSeek V3"},
            {"id": "meta-llama/llama-3.3-70b-instruct",       "name": "Llama 3.3 70B"},
            {"id": "qwen/qwen3-235b-a22b",                    "name": "Qwen 3 235B"},
            {"id": "qwen/qwen2.5-72b-instruct",               "name": "Qwen 2.5 72B"},
        ],
    },

    # ─── NVIDIA NIM ────────────────────────────────────────────────────────────
    "NVIDIA": {
        "name": "NVIDIA NIM",
        "icon": "▰",
        "color": "#76b900",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "api_key_env": "NVIDIA_API_KEY",
        "models_fetch_url": "https://integrate.api.nvidia.com/v1/models",
        "auth_url": "https://build.nvidia.com/settings/api-keys",
        "supports_web_login": True,
        "models": [
            {"id": "nvidia/nemotron-3-ultra",                          "name": "Nemotron 3 Ultra"},
            {"id": "nvidia/nemotron-3-super",                            "name": "Nemotron 3 Super"},
            {"id": "nvidia/nemotron-3-nano-30b-a3b",                     "name": "Nemotron 3 Nano 30B (Free)"},
            {"id": "nvidia/nemotron-4-340b-instruct",                    "name": "Nemotron 4 340B"},
            {"id": "nvidia/llama-3.1-nemotron-70b-instruct",             "name": "Nemotron 70B"},
            {"id": "nvidia/neutron-8b-instruct",                         "name": "Neutron 8B (Free)"},
            {"id": "meta/llama-4-maverick-17b-128e-instruct",           "name": "Llama 4 Maverick"},
            {"id": "meta/llama-4-scout-17b-16e-instruct",                "name": "Llama 4 Scout"},
            {"id": "meta/llama-3.1-405b-instruct",                       "name": "Llama 3.1 405B"},
            {"id": "deepseek-ai/deepseek-r1",                            "name": "DeepSeek R1"},
            {"id": "deepseek-ai/deepseek-v3.1",                          "name": "DeepSeek V3.1"},
            {"id": "deepseek-ai/deepseek-v4-flash",                      "name": "DeepSeek V4 Flash"},
            {"id": "qwen/qwen3-235b-a22b",                               "name": "Qwen 3 235B"},
            {"id": "qwen/qwen2.5-72b-instruct",                          "name": "Qwen 2.5 72B"},
            {"id": "mistralai/mistral-large",                            "name": "Mistral Large"},
        ],
    },

    # ─── Chinese / Asian Providers ─────────────────────────────────────────────
    "MoonshotAI": {
        "name": "Moonshot AI (Kimi)",
        "icon": "☾",
        "color": "#4f46e5",
        "base_url": "https://api.moonshot.ai/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "models_fetch_url": "https://api.moonshot.ai/v1/models",
        "models": [
            {"id": "kimi-k2.6",        "name": "Kimi K2.6"},
            {"id": "kimi-k2.5",        "name": "Kimi K2.5"},
            {"id": "kimi-k2-0905-preview", "name": "Kimi K2 0905 Preview"},
            {"id": "kimi-k2-turbo-preview", "name": "Kimi K2 Turbo Preview"},
            {"id": "kimi-k2-thinking", "name": "Kimi K2 Thinking"},
            {"id": "kimi-k2-thinking-turbo", "name": "Kimi K2 Thinking Turbo"},
        ],
    },
    "ZhipuAI": {
        "name": "Zhipu AI (GLM)",
        "icon": "⬡",
        "color": "#3b82f6",
        "base_url": "https://api.z.ai/api/paas/v4",
        "api_key_env": "ZHIPUAI_API_KEY",
        "models": [
            {"id": "glm-5.2",       "name": "GLM 5.2"},
            {"id": "glm-5.2[1m]",   "name": "GLM 5.2 1M"},
            {"id": "glm-5.1",       "name": "GLM 5.1"},
            {"id": "glm-5",         "name": "GLM 5"},
        ],
    },
    "Minimax": {
        "name": "MiniMax",
        "icon": "◎",
        "color": "#7c3aed",
        "base_url": "https://api.minimaxi.chat/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models": [
            {"id": "MiniMax-M3",      "name": "MiniMax M3"},
            {"id": "MiniMax-M2.7",    "name": "MiniMax M2.7"},
            {"id": "MiniMax-M2.5",    "name": "MiniMax M2.5"},
            {"id": "MiniMax-Text-01", "name": "MiniMax Text 01"},
            {"id": "abab6.5s-chat",   "name": "ABAB 6.5S"},
        ],
    },
    "MiMo": {
        "name": "MiMo (Xiaomi)",
        "icon": "禾",
        "color": "#ff6900",
        "base_url": "https://token-plan-sgp.xiaomimimo.com/v1",
        "api_key_env": "MIMO_API_KEY",
        "tier": "Token Plan",
        "api_key_header": "api-key",
        "auth_url": "https://mimo.mi.com/docs/en-US/tokenplan/Token%20Plan/subscription",
        "supports_web_login": True,
        "requires_api_key": True,
        "models": [
            {"id": "mimo-v2.5-pro",                 "name": "MiMo V2.5 Pro"},
            {"id": "mimo-v2.5",                     "name": "MiMo V2.5"},
            {"id": "mimo-v2.5-asr",                 "name": "MiMo V2.5 ASR"},
            {"id": "mimo-v2.5-tts",                 "name": "MiMo V2.5 TTS"},
            {"id": "mimo-v2.5-tts-voiceclone",      "name": "MiMo V2.5 TTS Voice Clone"},
            {"id": "mimo-v2.5-tts-voicedesign",     "name": "MiMo V2.5 TTS Voice Design"},
        ],
    },
    "AlibabaDashScope": {
        "name": "Alibaba (Qwen)",
        "icon": "◈",
        "color": "#f97316",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models": [
            {"id": "qwen-max",               "name": "Qwen Max"},
            {"id": "qwen-plus",              "name": "Qwen Plus"},
            {"id": "qwen-turbo",             "name": "Qwen Turbo"},
            {"id": "qwen3-235b-a22b",        "name": "Qwen 3 235B"},
            {"id": "qwen3-32b",              "name": "Qwen 3 32B"},
            {"id": "qwen2.5-72b-instruct",   "name": "Qwen 2.5 72B"},
            {"id": "qwq-32b",                "name": "QwQ 32B (Reasoning)"},
        ],
    },

    # ─── Enterprise / Specialized ──────────────────────────────────────────────
    "AzureOpenAI": {
        "name": "Azure OpenAI",
        "icon": "⊞",
        "color": "#0078d4",
        "base_url": "",
        "api_key_env": "AZURE_OPENAI_API_KEY",
        "requires_base_url": True,
        "models": [
            {"id": "gpt-4.1",       "name": "GPT-4.1"},
            {"id": "gpt-4.1-mini",  "name": "GPT-4.1 Mini"},
            {"id": "gpt-4o",        "name": "GPT-4o"},
            {"id": "gpt-4o-mini",   "name": "GPT-4o Mini"},
            {"id": "o4-mini",       "name": "o4 Mini"},
            {"id": "o3",            "name": "o3"},
        ],
    },
    "UpstageAI": {
        "name": "Upstage AI",
        "icon": "↑",
        "color": "#6366f1",
        "base_url": "https://api.upstage.ai/v1",
        "api_key_env": "UPSTAGE_API_KEY",
        "models": [
            {"id": "solar-pro",  "name": "Solar Pro"},
            {"id": "solar-mini", "name": "Solar Mini"},
        ],
    },
    "VeniceAI": {
        "name": "Venice AI",
        "icon": "⛵",
        "color": "#0891b2",
        "base_url": "https://api.venice.ai/api/v1",
        "api_key_env": "VENICE_API_KEY",
        "models": [
            {"id": "llama-3.3-70b",              "name": "Llama 3.3 70B"},
            {"id": "deepseek-r1-671b",           "name": "DeepSeek R1"},
            {"id": "qwen3-235b",                 "name": "Qwen 3 235B"},
            {"id": "mistral-31-24b",             "name": "Mistral 3.1 24B"},
        ],
    },
    "CloudflareAI": {
        "name": "Cloudflare Workers AI",
        "icon": "☁",
        "color": "#f6821f",
        "base_url": "",
        "api_key_env": "CLOUDFLARE_API_TOKEN",
        "requires_base_url": True,
        "models": [
            {"id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast", "name": "Llama 3.3 70B (Free)"},
            {"id": "@cf/meta/llama-3.1-70b-instruct",          "name": "Llama 3.1 70B (Free)"},
            {"id": "@cf/meta/llama-3.1-8b-instruct",           "name": "Llama 3.1 8B (Free)"},
            {"id": "@cf/deepseek-ai/deepseek-r1",              "name": "DeepSeek R1 (Free)"},
            {"id": "@cf/qwen/qwen2.5-coder-32b-instruct",      "name": "Qwen 2.5 Coder (Free)"},
            {"id": "@cf/mistral/mistral-7b-instruct-v0.2",     "name": "Mistral 7B (Free)"},
        ],
    },

    # ─── OpenCode / 9Router Ecosystem ─────────────────────────────────────────
    "OpenCodeZen": {
        "name": "OpenCode Zen (Free)",
        "icon": "◐",
        "color": "#22c55e",
        "base_url": "https://opencode.ai/zen/v1",
        "api_key_env": "OPENCODE_ZEN_API_KEY",
        "models_fetch_url": "https://opencode.ai/zen/v1/models",
        "tier": "Free",
        "requires_api_key": True,
        "auth_url": "https://opencode.ai/auth",
        "supports_web_login": True,
        "models": OPENCODE_ZEN_FREE_MODELS,
    },
    "KiroAI": {
        "name": "Kiro AI (Free)",
        "icon": "◭",
        "color": "#a855f7",
        "base_url": "",
        "api_key_env": "KIRO_API_KEY",
        "tier": "Free",
        "requires_base_url": True,
        "models": [
            {"id": "kr/claude-sonnet-5",       "name": "Claude Sonnet 5 (Free)"},
            {"id": "kr/claude-opus-4-8",       "name": "Claude Opus 4.8 (Free)"},
            {"id": "kr/claude-opus-4-6",       "name": "Claude Opus 4.6 (Free)"},
            {"id": "kr/glm-5.2",               "name": "GLM 5.2 (Free)"},
            {"id": "kr/glm-5",                 "name": "GLM 5 (Free)"},
            {"id": "kr/minimax-m3",            "name": "MiniMax M3 (Free)"},
            {"id": "kr/minimax-m2.5",          "name": "MiniMax M2.5 (Free)"},
            {"id": "kr/mimo-v2.5-free",        "name": "MiMo V2.5 (Free)"},
        ],
    },
    "SiliconFlow": {
        "name": "SiliconFlow",
        "icon": "≈",
        "color": "#2563eb",
        "base_url": "https://api.siliconflow.com/v1",
        "api_key_env": "SILICONFLOW_API_KEY",
        "models": [
            {"id": "deepseek-ai/DeepSeek-V3",              "name": "DeepSeek V3 (Free)"},
            {"id": "deepseek-ai/DeepSeek-R1",              "name": "DeepSeek R1 (Free)"},
            {"id": "Qwen/Qwen3-235B-A22B",                 "name": "Qwen 3 235B"},
            {"id": "Qwen/Qwen2.5-Coder-32B-Instruct",      "name": "Qwen 2.5 Coder 32B (Free)"},
            {"id": "THUDM/glm-4-9b-chat",                  "name": "GLM-4 9B (Free)"},
        ],
    },
    "Nebius": {
        "name": "Nebius AI",
        "icon": "◇",
        "color": "#0ea5e9",
        "base_url": "https://api.studio.nebius.ai/v1",
        "api_key_env": "NEBIUS_API_KEY",
        "models": [
            {"id": "deepseek-ai/DeepSeek-R1",              "name": "DeepSeek R1"},
            {"id": "deepseek-ai/DeepSeek-V3",              "name": "DeepSeek V3"},
            {"id": "meta-llama/Llama-3.3-70B-Instruct",    "name": "Llama 3.3 70B"},
            {"id": "Qwen/Qwen3-235B-A22B",                 "name": "Qwen 3 235B"},
        ],
    },
    "NineRouter": {
        "name": "9Router (Gateway)",
        "icon": "⑨",
        "color": "#f59e0b",
        "base_url": "http://localhost:20128/v1",
        "api_key_env": "NINEROUTER_API_KEY",
        "tier": "Gateway",
        "auth_url": "http://localhost:20128/dashboard",
        "supports_web_login": True,
        "models": [
            {"id": "kr/claude-sonnet-5",         "name": "Claude Sonnet 5 (via Kiro Free)"},
            {"id": "kr/claude-opus-4-8",         "name": "Claude Opus 4.8 (via Kiro Free)"},
            {"id": "kr/glm-5.2",                 "name": "GLM 5.2 (Free)"},
            {"id": "kr/minimax-m3",              "name": "MiniMax M3 (Free)"},
            {"id": "oc/mimo-v2.5-free",          "name": "MiMo V2.5 (OpenCode Free)"},
            {"id": "oc/nemotron-3-ultra-free",   "name": "Nemotron 3 Ultra (OpenCode Free)"},
            {"id": "oc/big-pickle",              "name": "Big Pickle (OpenCode Free)"},
            {"id": "oc/qwen3-coder",             "name": "OpenCode Qwen3 Coder (Free)"},
            {"id": "if/kimi-k2.6",               "name": "Kimi K2.6 (Free)"},
            {"id": "vertex/gemini-3.5-flash",    "name": "Gemini 3.5 Flash (Vertex)"},
            {"id": "auto",                       "name": "Auto (3-Tier Fallback)"},
        ],
    },

    # ─── Local / Self-hosted ───────────────────────────────────────────────────
    "Ollama": {
        "name": "Ollama (Local)",
        "icon": "⊙",
        "color": "#6b7280",
        "base_url": "http://localhost:11434/v1",
        "api_key_env": "",
        "is_local": True,
        "models": [
            {"id": "llama3.2",          "name": "Llama 3.2"},
            {"id": "llama3.1",          "name": "Llama 3.1"},
            {"id": "llama4",            "name": "Llama 4 Scout"},
            {"id": "qwen3",             "name": "Qwen 3"},
            {"id": "qwen2.5-coder",     "name": "Qwen 2.5 Coder"},
            {"id": "deepseek-r1",       "name": "DeepSeek R1"},
            {"id": "deepseek-v3",       "name": "DeepSeek V3"},
            {"id": "mistral",           "name": "Mistral"},
            {"id": "codellama",         "name": "Code Llama"},
            {"id": "phi4",              "name": "Phi 4"},
            {"id": "gemma3",            "name": "Gemma 3"},
        ],
    },
    "LMStudio": {
        "name": "LM Studio (Local)",
        "icon": "⊡",
        "color": "#6b7280",
        "base_url": "http://localhost:1234/v1",
        "api_key_env": "",
        "is_local": True,
        "models": [
            {"id": "local-model", "name": "Local Model"},
        ],
    },
    "OpenAICompatible": {
        "name": "Custom OpenAI-Compatible",
        "icon": "⬡",
        "color": "#64748b",
        "base_url": "",
        "api_key_env": "",
        "requires_base_url": True,
        "models": [
            {"id": "custom-model", "name": "Custom Model"},
        ],
    },
}


def find_provider_for_model(model_id: str):
    """Return (provider_name, provider_def) that owns model_id, else (None, None).

    Resolution is registry-driven so routing never depends on per-provider
    config.json having a cached 'models' list.
    """
    if not model_id:
        return None, None
    if model_id.startswith("claude-code/"):
        return "ClaudeCodeSubscription", PROVIDER_REGISTRY["ClaudeCodeSubscription"]
    if model_id.startswith("codex/"):
        return "CodexSubscription", PROVIDER_REGISTRY["CodexSubscription"]
    if model_id.startswith("opencode/"):
        return "OpenCodeZen", PROVIDER_REGISTRY["OpenCodeZen"]
    if model_id.startswith("mimo-"):
        return "MiMo", PROVIDER_REGISTRY["MiMo"]
    for provider_name, pdef in PROVIDER_REGISTRY.items():
        for model in pdef.get("models", []):
            if isinstance(model, dict) and model.get("id") == model_id:
                return provider_name, pdef
    return None, None
