name: Smoke Test
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VSCODE_SKIP_NODE_VERSION_CHECK: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: npm run compile-client
