// @ts-nocheck
import { existsSync } from 'fs';

export const dirs = [
	'',
	'tools/builder',
	'plugins/built-in/configuration-editing',
	'plugins/built-in/copilot',
	'plugins/built-in/css-language-features',
	'plugins/built-in/css-language-features/server',
	'plugins/built-in/debug-auto-launch',
	'plugins/built-in/debug-server-ready',
	'plugins/built-in/emmet',
	'plugins/built-in/extension-editing',
	'plugins/built-in/git',
	'plugins/built-in/git-base',
	'plugins/built-in/github',
	'plugins/built-in/github-authentication',
	'plugins/built-in/grunt',
	'plugins/built-in/gulp',
	'plugins/built-in/html-language-features',
	'plugins/built-in/html-language-features/server',
	'plugins/built-in/ipynb',
	'plugins/built-in/jake',
	'plugins/built-in/json-language-features',
	'plugins/built-in/json-language-features/server',
	'plugins/built-in/markdown-language-features',
	'plugins/built-in/markdown-math',
	'plugins/built-in/media-preview',
	'plugins/built-in/merge-conflict',
	'plugins/built-in/mermaid-markdown-features',
	'plugins/built-in/microsoft-authentication',
	'plugins/built-in/notebook-renderers',
	'plugins/built-in/npm',
	'plugins/built-in/php-language-features',
	'plugins/built-in/references-view',
	'plugins/built-in/search-result',
	'plugins/built-in/simple-browser',
	'plugins/built-in/tunnel-forwarding',
	'plugins/built-in/terminal-suggest',
	'plugins/built-in/typescript-language-features',
	'plugins/built-in/vscode-api-tests',
	'plugins/built-in/vscode-colorize-tests',
	'plugins/built-in/vscode-colorize-perf-tests',
	'plugins/built-in/vscode-test-resolver',
	'remote',
	'remote/web',
	'test/automation',
	'test/integration/browser',
	'test/monaco',
	'test/smoke',
	'test/mcp',
];

export function dirsWithPackageJson(): string[] {
	return dirs.filter(dir => existsSync(`${import.meta.dirname}/../../${dir}/package.json`));
}
